class HrisIntegrationsService::AdpWorkforceNowU::StaticAdpStateCodesList
  cattr_accessor :static_state_codes
  @@static_state_codes = { codes: [
        {"code": "Abū Z̧aby - Abu Dhabi", "category": "AE"}, {"code": "Ajmān", "category": "AE"}, {"code": "Al Fujayrah", "category": "AE"},
        {"code": "Ash Shāriqah - Sharjah", "category": "AE"}, {"code": "Dubayy - Dubai", "category": "AE"}, {"code": "Ra’s al Khaymah", "category": "AE"},
        {"code": "Umm al Qaywayn", "category": "AE"}, {"code": "Buenos Aires City", "category": "AR"}, {"code": "Buenos Aires", "category": "AR"},
        {"code": "Catamarca", "category": "AR"}, {"code": "Chaco", "category": "AR"}, {"code": "Chubut", "category": "AR"},
        {"code": "Córdoba", "category": "AR"}, {"code": "Corrientes", "category": "AR"}, {"code": " Entre Ríos", "category": "AR"},
        {"code": "Formosa", "category": "AR"}, {"code": "Jujuy", "category": "AR"}, {"code": "La Pampa", "category": "AR"},
        {"code": "La Rioja", "category": "AR"}, {"code": "Mendoza", "category": "AR"}, {"code": "Misiones", "category": "AR"},
        {"code": "Neuquén", "category": "AR"}, {"code": "Río Negro", "category": "AR"}, {"code": "Salta", "category": "AR"},
        {"code": "San Juan", "category": "AR"}, {"code": "San Luis", "category": "AR"}, {"code": "Santa Cruz", "category": "AR"},
        {"code": "Santa Fe", "category": "AR"}, {"code": "Santiago del Estero", "category": "AR"}, {"code": "Tierra del Fuego", "category": "AR"},
        {"code": "Tucumán", "category": "AR"}, {"code": "Burgenland", "category": "AT"}, {"code": "Kärnten", "category": "AT"},
        {"code": "Niederösterreich", "category": "AT"}, {"code": "Oberösterreich", "category": "AT"}, {"code": "Salzburg", "category": "AT"},
        {"code": "Steiermark", "category": "AT"}, {"code": "Tirol", "category": "AT"}, {"code": "Vorarlberg", "category": "AT"},
        {"code": "Wien", "category": "AT"}, {"code": "Ashmore and Cartier Islands", "category": "AU"}, {"code": "Australian Antarctic Territory", "category": "AU"},
        {"code": "Australian Capital Territory", "category": "AU"}, {"code": "Christmas Island", "category": "AU"}, {"code": "Cocos or Keeling Islands", "category": "AU"},
        {"code": "Coral Sea Islands", "category": "AU"}, {"code": "Heard Island and McDonald Islands", "category": "AU"}, {"code": "Jervis Bay Territory", "category": "AU"},
        {"code": "New South Wales", "category": "AU"}, {"code": "Norfolk Island", "category": "AU"}, {"code": "Northern Territory", "category": "AU"},
        {"code": "Queensland", "category": "AU"}, {"code": "South Australia", "category": "AU"}, {"code": "Tasmania", "category": "AU"},
        {"code": "Victoria", "category": "AU"}, {"code": "Western Australia", "category": "AU"}, {"code": "Barisal", "category": "BD"},
        {"code": "Chittagong", "category": "BD"}, {"code": "Dhaka", "category": "BD"}, {"code": "Khulna", "category": "BD"},
        {"code": "Rajshahi", "category": "BD"}, {"code": "Rangpur", "category": "BD"}, {"code": "Sylhet", "category": "BD"},
        {"code": "Brussels Hoofdstedelijk Gewest", "category": "BE"}, {"code": "Antwerpen", "category": "BE"}, {"code": "Vlaams-Brabant", "category": "BE"},
        {"code": "Vlaamse Gewest", "category": "BE"},{"code": "Limburg", "category": "BE"},{"code": "Oost-Vlaanderen", "category": "BE"},
        {"code": "West-Vlaanderen", "category": "BE"}, {"code": "wallonne, Région", "category": "BE"},{"code": "Brabant wallon", "category": "BE"},
        {"code": "Hainaut", "category": "BE"}, {"code": "Liège", "category": "BE"}, {"code": "Luxembourg", "category": "BE"}, {"code": "Namur", "category": "BE"},
        {"code": "Burgas", "category": "BG"},{"code": "Grad Sofiya", "category": "BG"},{"code": "Khaskovo", "category": "BG"},{"code": "Lovech", "category": "BG"},
        {"code": "Mikhaylovgrad", "category": "BG"}, {"code": "Plovdiv", "category": "BG"}, {"code": "Razgrad", "category": "BG"}, {"code": "Sofiya", "category": "BG"},
        {"code": "Varna", "category": "BG"},{"code": "Acre", "category": "BR"},{"code": "Alagoas", "category": "BR"},{"code": "Amapá", "category": "BR"},
        {"code": "Amazonas", "category": "BR"},{"code": "Bahia", "category": "BR"},{"code": "Ceará", "category": "BR"},{"code": "Distrito Federal", "category": "BR"},
        {"code": "Espírito Santo", "category": "BR"},{"code": "Goiás", "category": "BR"},{"code": "Maranhão", "category": "BR"},{"code": "Mato Grosso", "category": "BR"},
        {"code": "Mato Grosso do Sul", "category": "BR"},{"code": "Minas Gerais", "category": "BR"},{"code": "Pará", "category": "BR"},{"code": "Paraíba", "category": "BR"},
        {"code": "Parana", "category": "BR"}, {"code": "Pernambuco", "category": "BR"}, {"code": "Piauí", "category": "BR"}, {"code": "Rio de Janeiro", "category": "BR"},
        {"code": "Rio Grande do Norte", "category": "BR"}, {"code": "Rio Grande do Sul", "category": "BR"}, {"code": "Rondônia", "category": "BR"}, {"code": "Roraima", "category": "BR"},
        {"code": "Santa Catarina", "category": "BR"}, {"code": "São Paulo", "category": "BR"}, {"code": "Sergipe", "category": "BR"}, {"code": "Tocantins", "category": "BR"},
        {"code": "AB", "category": "CA"}, {"code": "AB", "category": "CA"}, {"code": "BC", "category": "CA"}, {"code": "BC", "category": "CA"},
        {"code": "MB", "category": "CA"}, {"code": "MB", "category": "CA"}, {"code": "NB", "category": "CA"}, {"code": "NB", "category": "CA"}, {"code": "NL", "category": "CA"},
        {"code": "NL", "category": "CA"}, {"code": "NS", "category": "CA"}, {"code": "NS", "category": "CA"}, {"code": "NT", "category": "CA"}, {"code": "NT", "category": "CA"},
        {"code": "NU", "category": "CA"}, {"code": "NU", "category": "CA"}, {"code": "ON", "category": "CA"}, {"code": "ON", "category": "CA"}, {"code": "PE", "category": "CA"},
        {"code": "PE", "category": "CA"}, {"code": "QC", "category": "CA"}, {"code": "QC", "category": "CA"}, {"code": "SK", "category": "CA"}, {"code": "SK", "category": "CA"},
        {"code": "YT", "category": "CA"}, {"code": "YT", "category": "CA"}, {"code": "ZZ", "category": "CA"}, {"code": "ZZ", "category": "CA"}, {"code": "Aargau (de)", "category": "CH"},
        {"code": "Appenzell Ausserrhoden (de)", "category": "CH"}, {"code": "Appenzell Innerrhoden (de)", "category": "CH"}, {"code": "Basel-Landschaft (de)", "category": "CH"}, {"code": "Basel-Stadt (de)", "category": "CH"},
        {"code": "Bern (de), Berne (fr)", "category": "CH"}, {"code": "Fribourg (fr), Freiburg (de)", "category": "CH"}, {"code": "Genève (fr)", "category": "CH"}, {"code": "Glarus (de)", "category": "CH"},
        {"code": "Graubünden (de), Grigioni (it)", "category": "CH"}, {"code": "Jura (fr)", "category": "CH"}, {"code": "Luzern (de)", "category": "CH"}, {"code": "Neuchâtel (fr)", "category": "CH"},
        {"code": "Nidwalden (de)", "category": "CH"}, {"code": "Obwalden (de)", "category": "CH"}, {"code": "Sankt Gallen (de)", "category": "CH"}, {"code": "Schaffhausen (de)", "category": "CH"},
        {"code": "Schwyz (de)", "category": "CH"}, {"code": "Solothurn (de)", "category": "CH"}, {"code": "Thurgau (de)", "category": "CH"}, {"code": "Ticino (it)", "category": "CH"},
        {"code": "Uri (de)", "category": "CH"}, {"code": "Valais (fr), Wallis (de)", "category": "CH"}, {"code": "Vaud (fr)", "category": "CH"}, {"code": "Zug (de)", "category": "CH"},
        {"code": "Zürich (de)", "category": "CH"}, {"code": "Aisén del General Carlos Ibañez del Campo", "category": "CL"}, {"code": "Antofagasta", "category": "CL"}, {"code": "Araucanía", "category": "CL"},
        {"code": "Arica y Parinacota", "category": "CL"}, {"code": "Atacama", "category": "CL"}, {"code": "Bío-Bío", "category": "CL"}, {"code": "Coquimbo", "category": "CL"},
        {"code": "Libertador General Bernardo O'Higgins", "category": "CL"}, {"code": "Los Lagos", "category": "CL"}, {"code": "Los Ríos", "category": "CL"}, {"code": "Magallanes", "category": "CL"},
        {"code": "Maule", "category": "CL"}, {"code": "Región Metropolitana de Santiago", "category": "CL"}, {"code": "Tarapacá", "category": "CL"}, {"code": "Valparaíso", "category": "CL"},
        {"code": "Anhui", "category": "CN"}, {"code": "Aomen", "category": "CN"}, {"code": "Beijing", "category": "CN"}, {"code": "Chongqing", "category": "CN"},
        {"code": "Fujian", "category": "CN"}, {"code": "Gansu", "category": "CN"}, {"code": "Guangdong", "category": "CN"}, {"code": "Guangxi", "category": "CN"},
        {"code": "Guizhou", "category": "CN"}, {"code": "Hainan", "category": "CN"}, {"code": "Hebei", "category": "CN"}, {"code": "Heilongjiang", "category": "CN"},
        {"code": "Henan", "category": "CN"}, {"code": "Hubei", "category": "CN"}, {"code": "Hunan", "category": "CN"}, {"code": "Jiangsu", "category": "CN"},
        {"code": "Jiangxi", "category": "CN"}, {"code": "Jilin", "category": "CN"}, {"code": "Liaoning", "category": "CN"}, {"code": "Nei Mongol", "category": "CN"},
        {"code": "Ningxia", "category": "CN"}, {"code": "Qinghai", "category": "CN"}, {"code": "Shaanxi", "category": "CN"}, {"code": "Shandong", "category": "CN"},
        {"code": "Shanghai", "category": "CN"}, {"code": "Shanxi", "category": "CN"}, {"code": "Sichuan", "category": "CN"}, {"code": "Taiwan", "category": "CN"}, {"code": "Tianjin", "category": "CN"},
        {"code": "Xianggang", "category": "CN"}, {"code": "Xinjiang", "category": "CN"}, {"code": "Xizang", "category": "CN"}, {"code": "Yunnan", "category": "CN"}, {"code": "Zhejiang", "category": "CN"},
        {"code": "Distrito Capital de Bogotá", "category": "CO"}, {"code": "Amazonas", "category": "CO"}, {"code": "Antioquia", "category": "CO"}, {"code": "Arauca", "category": "CO"},
        {"code": "Atlántico", "category": "CO"}, {"code": "Bolívar", "category": "CO"}, {"code": "Boyacá", "category": "CO"}, {"code": "Caldas", "category": "CO"},
        {"code": "Caquetá", "category": "CO"}, {"code": "Casanare", "category": "CO"}, {"code": "Cauca", "category": "CO"}, {"code": "Cesar", "category": "CO"},
        {"code": "Cordoba", "category": "CO"}, {"code": "Cundinamarca", "category": "CO"}, {"code": "Chocó", "category": "CO"}, {"code": "Guainía", "category": "CO"}, {"code": "Guaviare", "category": "CO"},
        {"code": "Huila", "category": "CO"}, {"code": "La Guajira", "category": "CO"}, {"code": "Magdalena", "category": "CO"}, {"code": "Meta", "category": "CO"}, {"code": "Nariño", "category": "CO"}, {"code": "Norte de Santander", "category": "CO"},
        {"code": "Putumayo", "category": "CO"}, {"code": "Quindío", "category": "CO"}, {"code": "Risaralda", "category": "CO"}, {"code": "San Andrés, Providencia y Santa Catalina", "category": "CO"}, {"code": "Santander", "category": "CO"},
        {"code": "Sucre", "category": "CO"}, {"code": "Tolima", "category": "CO"}, {"code": "Valle del Cauca", "category": "CO"}, {"code": "Vaupés", "category": "CO"}, {"code": "Vichada", "category": "CO"}, {"code": "Alajuela", "category": "CR"},
        {"code": "Cartago", "category": "CR"}, {"code": "Guanacaste", "category": "CR"}, {"code": "Heredia", "category": "CR"}, {"code": "Limón", "category": "CR"}, {"code": "Puntarenas", "category": "CR"}, {"code": "San José", "category": "CR"}, {"code": "Praha 01", "category": "CZ"}, {"code": "Praha 02", "category": "CZ"},
        {"code": "Praha 03", "category": "CZ"}, {"code": "Praha 04", "category": "CZ"}, {"code": "Praha 05", "category": "CZ"}, {"code": "Praha 06", "category": "CZ"}, {"code": "Praha 07", "category": "CZ"}, {"code": "Praha 08", "category": "CZ"}, {"code": "Praha 09", "category": "CZ"},
        {"code": "Praha 10", "category": "CZ"}, {"code": "Praha 11", "category": "CZ"}, {"code": "Praha 12", "category": "CZ"}, {"code": "Praha 13", "category": "CZ"}, {"code": "Praha 14", "category": "CZ"}, {"code": "Praha 15", "category": "CZ"}, {"code": "Benešov", "category": "CZ"}, {"code": "Beroun", "category": "CZ"},
        {"code": "Kladno", "category": "CZ"}, {"code": "Kolín", "category": "CZ"}, {"code": "Kutná Hora", "category": "CZ"}, {"code": "Mělník", "category": "CZ"}, {"code": "Mladá Boleslav", "category": "CZ"}, {"code": "Nymburk", "category": "CZ"}, {"code": "Praha-východ", "category": "CZ"},
        {"code": "Praha-západ", "category": "CZ"}, {"code": "Příbram", "category": "CZ"}, {"code": "Rakovník", "category": "CZ"}, {"code": "České Budějovice", "category": "CZ"}, {"code": "Český Krumlov", "category": "CZ"}, {"code": "Jindřichův Hradec", "category": "CZ"}, {"code": "Písek", "category": "CZ"},
        {"code": "Prachatice", "category": "CZ"}, {"code": "Strakonice", "category": "CZ"}, {"code": "Tábor", "category": "CZ"}, {"code": "Domažlice", "category": "CZ"}, {"code": "Klatovy", "category": "CZ"}, {"code": "Plzeň-město", "category": "CZ"}, {"code": "Plzeň-jih", "category": "CZ"}, {"code": "Plzeň-sever", "category": "CZ"}, {"code": "Rokycany", "category": "CZ"},
        {"code": "Tachov", "category": "CZ"}, {"code": "H~eb !Cheb", "category": "CZ"}, {"code": "Karlovy Vary", "category": "CZ"}, {"code": "Sokolov", "category": "CZ"}, {"code": "Děčín", "category": "CZ"}, {"code": "Chomutov", "category": "CZ"}, {"code": "Litoměřice", "category": "CZ"},
        {"code": "Louny", "category": "CZ"}, {"code": "Most", "category": "CZ"}, {"code": "Teplice", "category": "CZ"}, {"code": "Ústí nad Labem", "category": "CZ"}, {"code": "Česká Lípa", "category": "CZ"}, {"code": "Jablonec nad Nisou", "category": "CZ"}, {"code": "Liberec", "category": "CZ"},
        {"code": "Semily", "category": "CZ"}, {"code": "Hradec Králové", "category": "CZ"}, {"code": "Jičín", "category": "CZ"}, {"code": "Náchod", "category": "CZ"}, {"code": "Rychnov nad Kněžnou", "category": "CZ"}, {"code": "Trutnov", "category": "CZ"}, {"code": "Chrudim", "category": "CZ"},
        {"code": "Pardubice", "category": "CZ"}, {"code": "Svitavy", "category": "CZ"}, {"code": "Ústí nad Orlicí", "category": "CZ"}, {"code": "Havlíčkův Brod", "category": "CZ"}, {"code": "Jihlava", "category": "CZ"}, {"code": "Pelhřimov", "category": "CZ"}, {"code": "Třebíč", "category": "CZ"},
        {"code": "Žďár nad Sázavou", "category": "CZ"}, {"code": "Blansko", "category": "CZ"}, {"code": "Brno-město", "category": "CZ"}, {"code": "Brno-venkov", "category": "CZ"}, {"code": "Břeclav", "category": "CZ"}, {"code": "Hodonín", "category": "CZ"},
        {"code": "Vyškov", "category": "CZ"}, {"code": "Znojmo", "category": "CZ"}, {"code": "Jeseník", "category": "CZ"}, {"code": "Olomouc", "category": "CZ"}, {"code": "Prostějov", "category": "CZ"}, {"code": "Přerov", "category": "CZ"},
        {"code": "Šumperk", "category": "CZ"}, {"code": "Kroměříž", "category": "CZ"}, {"code": "Uherské Hradiště", "category": "CZ"}, {"code": "Vsetín", "category": "CZ"}, {"code": "Zlín", "category": "CZ"}, {"code": "Bruntál", "category": "CZ"}, {"code": "Frýdek-Místek", "category": "CZ"},
        {"code": "Karviná", "category": "CZ"}, {"code": "Nový Jičín", "category": "CZ"}, {"code": "Opava", "category": "CZ"}, {"code": "Ostrava-město", "category": "CZ"}, {"code": "Jihočeský kraj", "category": "CZ"}, {"code": "Jihomoravský kraj", "category": "CZ"},
        {"code": "Karlovarský kraj", "category": "CZ"}, {"code": "Královéhradecký kraj", "category": "CZ"}, {"code": "Liberecký kraj", "category": "CZ"}, {"code": "Moravskoslezský kraj", "category": "CZ"}, {"code": "Olomoucký kraj", "category": "CZ"}, {"code": "Pardubický kraj", "category": "CZ"},
        {"code": "Plzeňský kraj", "category": "CZ"}, {"code": "Praha, hlavní město", "category": "CZ"}, {"code": "Středočeský kraj", "category": "CZ"}, {"code": "Ústecký kraj", "category": "CZ"}, {"code": "Vysočina", "category": "CZ"}, {"code": "Zlínský kraj", "category": "CZ"}, {"code": "Baden-Württemberg", "category": "DE"},
        {"code": "Bayern", "category": "DE"}, {"code": "Berlin", "category": "DE"}, {"code": "Brandenburg", "category": "DE"}, {"code": "Bremen", "category": "DE"}, {"code": "Hamburg", "category": "DE"},
        {"code": "Hessen", "category": "DE"}, {"code": "Mecklenburg-Vorpommern", "category": "DE"}, {"code": "Niedersachsen", "category": "DE"}, {"code": "Nordrhein-Westfalen", "category": "DE"}, {"code": "Rheinland-Pfalz", "category": "DE"},
        {"code": "Saarland", "category": "DE"}, {"code": "Sachsen", "category": "DE"}, {"code": "Sachsen-Anhalt", "category": "DE"}, {"code": "Schleswig-Holstein", "category": "DE"}, {"code": "Thüringen", "category": "DE"},
        {"code": "Hovedstaden", "category": "DK"}, {"code": "Midtjylland", "category": "DK"}, {"code": "Nordjylland", "category": "DK"}, {"code": "Sjaelland", "category": "DK"}, {"code": "Syddanmark", "category": "DK"}, {"code": "Azua", "category": "DO"},
        {"code": "Baoruco", "category": "DO"}, {"code": "Barahona", "category": "DO"}, {"code": "Dajabón", "category": "DO"}, {"code": "Distrito Nacional", "category": "DO"}, {"code": "Duarte", "category": "DO"}, {"code": "Elías Piña", "category": "DO"},
        {"code": "El Seibo", "category": "DO"}, {"code": "Espaillat", "category": "DO"}, {"code": "Hato Mayor", "category": "DO"}, {"code": "Hermanas Mirabal", "category": "DO"}, {"code": "Independencia", "category": "DO"}, {"code": "La Altagracia", "category": "DO"},
        {"code": "La Romana", "category": "DO"}, {"code": "La Vega", "category": "DO"}, {"code": "María Trinidad Sánchez", "category": "DO"}, {"code": "Monseñor Nouel", "category": "DO"}, {"code": "Monte Cristi", "category": "DO"}, {"code": "Monte Plata", "category": "DO"},
        {"code": "Pedernales", "category": "DO"}, {"code": "Peravia", "category": "DO"}, {"code": "Puerto Plata", "category": "DO"}, {"code": "Samaná", "category": "DO"}, {"code": "Sánchez Ramírez", "category": "DO"}, {"code": "San Cristóbal", "category": "DO"}, {"code": "San José de Ocoa", "category": "DO"},
        {"code": "San Juan", "category": "DO"}, {"code": "San Pedro de Macoris", "category": "DO"}, {"code": "Santiago", "category": "DO"}, {"code": "Santiago Rodriguez", "category": "DO"}, {"code": "Santo Domingo", "category": "DO"}, {"code": "Valverde", "category": "DO"}, {"code": "Adrar", "category": "DZ"},
        {"code": "Aïn Defla", "category": "DZ"}, {"code": "Aïn Témouchent", "category": "DZ"}, {"code": "Alger", "category": "DZ"}, {"code": "Annaba", "category": "DZ"}, {"code": "Batna", "category": "DZ"}, {"code": "Béchar", "category": "DZ"},
        {"code": "Béjaïa", "category": "DZ"}, {"code": "Biskra", "category": "DZ"}, {"code": "Blida", "category": "DZ"}, {"code": "Bordj Bou Arréridj", "category": "DZ"}, {"code": "Bouira", "category": "DZ"}, {"code": "Boumerdès", "category": "DZ"}, {"code": "Chlef", "category": "DZ"},
        {"code": "Constantine", "category": "DZ"}, {"code": "Djelfa", "category": "DZ"}, {"code": "El Bayadh", "category": "DZ"}, {"code": "El Oued", "category": "DZ"}, {"code": "El Tarf", "category": "DZ"}, {"code": "Ghardaïa", "category": "DZ"},
        {"code": "Guelma", "category": "DZ"}, {"code": "Illizi", "category": "DZ"}, {"code": "Jijel", "category": "DZ"}, {"code": "Khenchela", "category": "DZ"}, {"code": "Laghouat", "category": "DZ"}, {"code": "Mascara", "category": "DZ"},
        {"code": "Médéa", "category": "DZ"}, {"code": "Mila", "category": "DZ"}, {"code": "Mostaganem", "category": "DZ"}, {"code": "Msila", "category": "DZ"}, {"code": "Naama", "category": "DZ"}, {"code": "Oran", "category": "DZ"},
        {"code": "Ouargla", "category": "DZ"}, {"code": "Oum el Bouaghi", "category": "DZ"}, {"code": "Relizane", "category": "DZ"}, {"code": "Saïda", "category": "DZ"}, {"code": "Sétif", "category": "DZ"}, {"code": "Sidi Bel Abbès", "category": "DZ"},
        {"code": "Skikda", "category": "DZ"}, {"code": "Souk Ahras", "category": "DZ"}, {"code": "Tamanghasset", "category": "DZ"}, {"code": "Tébessa", "category": "DZ"}, {"code": "Tiaret", "category": "DZ"}, {"code": "Tindouf", "category": "DZ"},
        {"code": "Tipaza", "category": "DZ"}, {"code": "Tissemsilt", "category": "DZ"}, {"code": "Tizi Ouzou", "category": "DZ"}, {"code": "Tlemcen", "category": "DZ"}, {"code": "Álava", "category": "ES"}, {"code": "Albacete", "category": "ES"},
        {"code": "Alicante", "category": "ES"}, {"code": "Almería", "category": "ES"}, {"code": "Asturias", "category": "ES"}, {"code": "Ávila", "category": "ES"}, {"code": "Badajoz", "category": "ES"}, {"code": "Balearic Islands", "category": "ES"},
        {"code": "Barcelona", "category": "ES"}, {"code": "Biscay", "category": "ES"}, {"code": "Burgos", "category": "ES"}, {"code": "Cáceres", "category": "ES"}, {"code": "Cádiz", "category": "ES"}, {"code": "Cantabria", "category": "ES"},
        {"code": "Castellón", "category": "ES"}, {"code": "Ceuta", "category": "ES"}, {"code": "Ciudad Real", "category": "ES"}, {"code": "Córdoba", "category": "ES"}, {"code": "Cuenca", "category": "ES"}, {"code": "Girona", "category": "ES"}, {"code": "Granada", "category": "ES"},
        {"code": "Guadalajara", "category": "ES"}, {"code": "Guipúzcoa", "category": "ES"}, {"code": "Huelva", "category": "ES"}, {"code": "Huesca", "category": "ES"}, {"code": "Jaén", "category": "ES"}, {"code": "La Coruña", "category": "ES"}, {"code": "La Rioja", "category": "ES"},
        {"code": "Las Palmas", "category": "ES"}, {"code": "León", "category": "ES"}, {"code": "Lleida", "category": "ES"}, {"code": "Lugo", "category": "ES"}, {"code": "Madrid", "category": "ES"}, {"code": "Málaga", "category": "ES"}, {"code": "Melilla", "category": "ES"}, {"code": "Murcia", "category": "ES"},
        {"code": "Navarra", "category": "ES"}, {"code": "Ourense", "category": "ES"}, {"code": "Palencia", "category": "ES"}, {"code": "Pontevedra", "category": "ES"}, {"code": "Salamanca", "category": "ES"}, {"code": "Santa Cruz de Tenerife", "category": "ES"}, {"code": "Segovia", "category": "ES"},
        {"code": "Sevilla", "category": "ES"}, {"code": "Soria", "category": "ES"}, {"code": "Tarragona", "category": "ES"}, {"code": "Teruel", "category": "ES"}, {"code": "Toledo", "category": "ES"}, {"code": "Valencia", "category": "ES"}, {"code": "Valladolid", "category": "ES"},
        {"code": "Zamora", "category": "ES"}, {"code": "Zaragoza", "category": "ES"}, {"code": "Ain", "category": "FR"}, {"code": "Aisne", "category": "FR"}, {"code": "Allier", "category": "FR"}, {"code": "Alpes-de-Haute-Provence", "category": "FR"}, {"code": "Alpes-Maritimes", "category": "FR"},
        {"code": "Ardèche", "category": "FR"}, {"code": "Ardennes", "category": "FR"}, {"code": "Ariège", "category": "FR"}, {"code": "Aube", "category": "FR"}, {"code": "Aude", "category": "FR"}, {"code": "Aveyron", "category": "FR"}, {"code": "Bas-Rhin", "category": "FR"},
        {"code": "Bouches-du-Rhône", "category": "FR"}, {"code": "Calvados", "category": "FR"}, {"code": "Cantal", "category": "FR"}, {"code": "Charente", "category": "FR"}, {"code": "Charente-Maritime", "category": "FR"}, {"code": "Cher", "category": "FR"}, {"code": "Corrèze", "category": "FR"},
        {"code": "Corse-du-Sud", "category": "FR"}, {"code": "Côte-d'Or", "category": "FR"}, {"code": "Côtes-d'Armor", "category": "FR"}, {"code": "Creuse", "category": "FR"}, {"code": "Deux-Sèvres", "category": "FR"}, {"code": "Dordogne", "category": "FR"}, {"code": "Doubs", "category": "FR"}, {"code": "Drôme", "category": "FR"},
        {"code": "Essonne", "category": "FR"}, {"code": "Eure", "category": "FR"}, {"code": "Eure-et-Loir", "category": "FR"}, {"code": "Finistère", "category": "FR"}, {"code": "Gard", "category": "FR"}, {"code": "Gers", "category": "FR"}, {"code": "Gironde", "category": "FR"},
        {"code": "Haute-Corse", "category": "FR"}, {"code": "Haute-Garonne", "category": "FR"}, {"code": "Haute-Loire", "category": "FR"}, {"code": "Haute-Marne", "category": "FR"}, {"code": "Hautes-Alpes", "category": "FR"}, {"code": "Haute-Saône", "category": "FR"}, {"code": "Haute-Savoie", "category": "FR"},
        {"code": "Hautes-Pyrénées", "category": "FR"}, {"code": "Haute-Vienne", "category": "FR"}, {"code": "Haut-Rhin", "category": "FR"}, {"code": "Hauts-de-Seine", "category": "FR"}, {"code": "Hérault", "category": "FR"}, {"code": "Ille-et-Vilaine", "category": "FR"}, {"code": "Indre", "category": "FR"},
        {"code": "Indre-et-Loire", "category": "FR"}, {"code": "Isère", "category": "FR"}, {"code": "Jura", "category": "FR"}, {"code": "Landes", "category": "FR"}, {"code": "Loire", "category": "FR"}, {"code": "Loire-Atlantique", "category": "FR"}, {"code": "Loiret", "category": "FR"},
        {"code": "Loir-et-Cher", "category": "FR"}, {"code": "Lot", "category": "FR"}, {"code": "Lot-et-Garonne", "category": "FR"}, {"code": "Lozère", "category": "FR"}, {"code": "Maine-et-Loire", "category": "FR"}, {"code": "Manche", "category": "FR"}, {"code": "Marne", "category": "FR"},
        {"code": "Mayenne", "category": "FR"},{"code": "Meurthe-et-Moselle", "category": "FR"},{"code": "Meuse", "category": "FR"},{"code": "Morbihan", "category": "FR"},{"code": "Moselle", "category": "FR"},{"code": "Nièvre", "category": "FR"},
        {"code": "Nord", "category": "FR"}, {"code": "Oise", "category": "FR"}, {"code": "Orne", "category": "FR"}, {"code": "Paris", "category": "FR"}, {"code": "Pas-de-Calais", "category": "FR"}, {"code": "Puy-de-Dôme", "category": "FR"},
        {"code": "Pyrénées-Atlantiques", "category": "FR"}, {"code": "Pyrénées-Orientales", "category": "FR"}, {"code": "Rhône", "category": "FR"}, {"code": "Saône-et-Loire", "category": "FR"}, {"code": "Sarthe", "category": "FR"}, {"code": "Savoie", "category": "FR"},
        {"code": "Seine-et-Marne", "category": "FR"}, {"code": "Seine-Maritime", "category": "FR"}, {"code": "Seine-Saint-Denis", "category": "FR"}, {"code": "Somme", "category": "FR"}, {"code": "Tarn", "category": "FR"}, {"code": "Tarn-et-Garonne", "category": "FR"},
        {"code": "Territoire de Belfort", "category": "FR"}, {"code": "Val-de-Marne", "category": "FR"}, {"code": "Val-d'Oise", "category": "FR"}, {"code": "Var", "category": "FR"}, {"code": "Vaucluse", "category": "FR"}, {"code": "Vendée", "category": "FR"},
        {"code": "Vienne", "category": "FR"}, {"code": "Vosges", "category": "FR"}, {"code": "Yonne", "category": "FR"}, {"code": "Yvelines", "category": "FR"}, {"code": "Aberdeen City", "category": "GB"}, {"code": "Aberdeenshire", "category": "GB"},
        {"code": "Angus", "category": "GB"}, {"code": "Antrim", "category": "GB"}, {"code": "Ards", "category": "GB"}, {"code": "Argyll and Bute", "category": "GB"}, {"code": "Armagh", "category": "GB"}, {"code": "Ballymena", "category": "GB"},
        {"code": "Ballymoney", "category": "GB"}, {"code": "Banbridge", "category": "GB"}, {"code": "Barking and Dagenham", "category": "GB"}, {"code": "Barnet", "category": "GB"}, {"code": "Barnsley", "category": "GB"}, {"code": "Bath and North East Somerset", "category": "GB"}, {"code": "Bedford", "category": "GB"},
        {"code": "Belfast", "category": "GB"}, {"code": "Bexley", "category": "GB"}, {"code": "Birmingham", "category": "GB"}, {"code": "Blackburn with Darwen", "category": "GB"}, {"code": "Blackpool", "category": "GB"}, {"code": "Blaenau Gwent", "category": "GB"}, {"code": "Bolton", "category": "GB"},
        {"code": "Bournemouth", "category": "GB"}, {"code": "Bracknell Forest", "category": "GB"}, {"code": "Bradford", "category": "GB"}, {"code": "Brent", "category": "GB"}, {"code": "Bridgend", "category": "GB"}, {"code": "Brighton and Hove", "category": "GB"}, {"code": "Bristol, City of", "category": "GB"}, {"code": "Bromley", "category": "GB"},
        {"code": "Buckinghamshire", "category": "GB"}, {"code": "Bury", "category": "GB"}, {"code": "Caerphilly", "category": "GB"}, {"code": "Calderdale", "category": "GB"}, {"code": "Cambridgeshire", "category": "GB"}, {"code": "Camden", "category": "GB"}, {"code": "Cardiff", "category": "GB"},
        {"code": "Carmarthenshire", "category": "GB"}, {"code": "Carrickfergus", "category": "GB"}, {"code": "Castlereagh", "category": "GB"}, {"code": "Central Bedfordshire", "category": "GB"}, {"code": "Ceredigion", "category": "GB"}, {"code": "Cheshire East", "category": "GB"}, {"code": "Cheshire West and Chester", "category": "GB"},
        {"code": "Clackmannanshire", "category": "GB"}, {"code": "Coleraine", "category": "GB"}, {"code": "Conwy", "category": "GB"}, {"code": "Cookstown", "category": "GB"}, {"code": "Cornwall", "category": "GB"}, {"code": "Coventry", "category": "GB"}, {"code": "Craigavon", "category": "GB"},
        {"code": "Croydon", "category": "GB"}, {"code": "Cumbria", "category": "GB"}, {"code": "Darlington", "category": "GB"}, {"code": "Denbighshire", "category": "GB"}, {"code": "Derby", "category": "GB"}, {"code": "Derbyshire", "category": "GB"}, {"code": "Derry", "category": "GB"}, {"code": "Devon", "category": "GB"}, {"code": "Doncaster", "category": "GB"}, {"code": "Dorset", "category": "GB"},
        {"code": "Down", "category": "GB"}, {"code": "Dudley", "category": "GB"}, {"code": "Dumfries and Galloway", "category": "GB"}, {"code": "Dundee City", "category": "GB"}, {"code": "Dungannon and South Tyrone", "category": "GB"}, {"code": "Durham, County", "category": "GB"}, {"code": "Ealing", "category": "GB"}, {"code": "East Ayrshire", "category": "GB"}, {"code": "East Dunbartonshire", "category": "GB"}, {"code": "East Lothian", "category": "GB"},
        {"code": "East Renfrewshire", "category": "GB"}, {"code": "East Riding of Yorkshire", "category": "GB"}, {"code": "East Sussex", "category": "GB"}, {"code": "Edinburgh, City of", "category": "GB"}, {"code": "Eilean Siar", "category": "GB"}, {"code": "Enfield", "category": "GB"}, {"code": "Essex", "category": "GB"}, {"code": "Falkirk", "category": "GB"}, {"code": "Fermanagh", "category": "GB"}, {"code": "Fife", "category": "GB"},
        {"code": "Flintshire", "category": "GB"}, {"code": "Gateshead", "category": "GB"}, {"code": "Glasgow City", "category": "GB"}, {"code": "Gloucestershire", "category": "GB"}, {"code": "Greenwich", "category": "GB"}, {"code": "Gwynedd", "category": "GB"}, {"code": "Hackney", "category": "GB"},
        {"code": "Halton", "category": "GB"}, {"code": "Hammersmith and Fulham", "category": "GB"}, {"code": "Hampshire", "category": "GB"}, {"code": "Haringey", "category": "GB"}, {"code": "Harrow", "category": "GB"}, {"code": "Hartlepool", "category": "GB"}, {"code": "Havering", "category": "GB"},
        {"code": "Herefordshire", "category": "GB"}, {"code": "Hertfordshire", "category": "GB"}, {"code": "Highland", "category": "GB"}, {"code": "Hillingdon", "category": "GB"}, {"code": "Hounslow", "category": "GB"}, {"code": "Inverclyde", "category": "GB"}, {"code": "Isle of Anglesey", "category": "GB"},
        {"code": "Isle of Wight", "category": "GB"}, {"code": "Islington", "category": "GB"}, {"code": "Kensington and Chelsea", "category": "GB"}, {"code": "Kent", "category": "GB"}, {"code": "Kingston upon Hull", "category": "GB"}, {"code": "Kingston upon Thames", "category": "GB"}, {"code": "Kirklees", "category": "GB"},
        {"code": "Knowsley", "category": "GB"}, {"code": "Lambeth", "category": "GB"}, {"code": "Lancashire", "category": "GB"}, {"code": "Larne", "category": "GB"}, {"code": "Leeds", "category": "GB"}, {"code": "Leicester", "category": "GB"}, {"code": "Leicestershire", "category": "GB"},
        {"code": "Lewisham", "category": "GB"}, {"code": "Limavady", "category": "GB"}, {"code": "Lincolnshire", "category": "GB"}, {"code": "Lisburn", "category": "GB"}, {"code": "Liverpool", "category": "GB"}, {"code": "London, City of", "category": "GB"}, {"code": "Luton", "category": "GB"}, {"code": "Magherafelt", "category": "GB"},
        {"code": "Manchester", "category": "GB"}, {"code": "Medway", "category": "GB"}, {"code": "Merthyr Tydfil", "category": "GB"}, {"code": "Merton", "category": "GB"}, {"code": "Middlesbrough", "category": "GB"}, {"code": "Midlothian", "category": "GB"},
        {"code": "Milton Keynes", "category": "GB"}, {"code": "Monmouthshire", "category": "GB"}, {"code": "Moray", "category": "GB"}, {"code": "Moyle", "category": "GB"}, {"code": "Neath Port Talbot", "category": "GB"}, {"code": "Newcastle upon Tyne", "category": "GB"}, {"code": "Newham", "category": "GB"},
        {"code": "Newport", "category": "GB"}, {"code": "Newry and Mourne District", "category": "GB"}, {"code": "Newtownabbey", "category": "GB"}, {"code": "Norfolk", "category": "GB"}, {"code": "North Ayrshire", "category": "GB"}, {"code": "North Down", "category": "GB"}, {"code": "North East Lincolnshire", "category": "GB"},
        {"code": "North Lanarkshire", "category": "GB"},{"code": "North Lincolnshire", "category": "GB"},{"code": "North Somerset", "category": "GB"},{"code": "North Tyneside", "category": "GB"},{"code": "North Yorkshire", "category": "GB"},{"code": "Northamptonshire", "category": "GB"},{"code": "Northumberland", "category": "GB"},{"code": "Nottingham", "category": "GB"},{"code": "Nottinghamshire", "category": "GB"},
        {"code": "Oldham", "category": "GB"}, {"code": "Omagh", "category": "GB"}, {"code": "Orkney Islands", "category": "GB"}, {"code": "Oxfordshire", "category": "GB"}, {"code": "Pembrokeshire", "category": "GB"}, {"code": "Perth and Kinross", "category": "GB"}, {"code": "Peterborough", "category": "GB"}, {"code": "Plymouth", "category": "GB"}, {"code": "Poole", "category": "GB"},
        {"code": "Portsmouth", "category": "GB"},
        {"code": "Powys", "category": "GB"},
        {"code": "Reading", "category": "GB"},
        {"code": "Redbridge", "category": "GB"},
        {"code": "Redcar and Cleveland", "category": "GB"},
        {"code": "Renfrewshire", "category": "GB"},
        {"code": "Rhondda Cynon Taff", "category": "GB"},
        {"code": "Richmond upon Thames", "category": "GB"},
        {"code": "Rochdale", "category": "GB"},
        {"code": "Rotherham", "category": "GB"},
        {"code": "Rutland", "category": "GB"},
        {"code": "Salford", "category": "GB"},
        {"code": "Sandwell", "category": "GB"},
        {"code": "Scottish Borders, The", "category": "GB"},
        {"code": "Sefton", "category": "GB"},
        {"code": "Sheffield", "category": "GB"},
        {"code": "Shetland Islands", "category": "GB"},
        {"code": "Shropshire", "category": "GB"},
        {"code": "Slough", "category": "GB"},
        {"code": "Solihull", "category": "GB"},
        {"code": "Somerset", "category": "GB"},
        {"code": "South Ayrshire", "category": "GB"},
        {"code": "South Gloucestershire", "category": "GB"},
        {"code": "South Lanarkshire", "category": "GB"},
        {"code": "South Tyneside", "category": "GB"},
        {"code": "Southampton", "category": "GB"},
        {"code": "Southend-on-Sea", "category": "GB"},
        {"code": "Southwark", "category": "GB"},
        {"code": "St. Helens", "category": "GB"},
        {"code": "Staffordshire", "category": "GB"},
        {"code": "Stirling", "category": "GB"},
        {"code": "Stockport", "category": "GB"},
        {"code": "Stockton-on-Tees", "category": "GB"},
        {"code": "Stoke-on-Trent", "category": "GB"},
        {"code": "Strabane", "category": "GB"},
        {"code": "Suffolk", "category": "GB"},
        {"code": "Sunderland", "category": "GB"},
        {"code": "Surrey", "category": "GB"},
        {"code": "Sutton", "category": "GB"},
        {"code": "Swansea", "category": "GB"},
        {"code": "Swindon", "category": "GB"},
        {"code": "Tameside", "category": "GB"},
        {"code": "Telford and Wrekin", "category": "GB"},
        {"code": "Thurrock", "category": "GB"},
        {"code": "Torbay", "category": "GB"},
        {"code": "Torfaen", "category": "GB"},
        {"code": "Tower Hamlets", "category": "GB"},
        {"code": "Trafford", "category": "GB"},
        {"code": "Vale of Glamorgan", "category": "GB"},
        {"code": "Wakefield", "category": "GB"},
        {"code": "Walsall", "category": "GB"},
        {"code": "Waltham Forest", "category": "GB"},
        {"code": "Wandsworth", "category": "GB"},
        {"code": "Warrington", "category": "GB"},
        {"code": "Warwickshire", "category": "GB"},
        {"code": "West Berkshire", "category": "GB"},
        {"code": "West Dunbartonshire", "category": "GB"},
        {"code": "West Lothian", "category": "GB"},
        {"code": "West Sussex", "category": "GB"},
        {"code": "Westminster", "category": "GB"},
        {"code": "Wigan", "category": "GB"},
        {"code": "Wiltshire", "category": "GB"},
        {"code": "Windsor and Maidenhead", "category": "GB"},
        {"code": "Wirral", "category": "GB"},
        {"code": "Wokingham", "category": "GB"},
        {"code": "Wolverhampton", "category": "GB"},
        {"code": "Worcestershire", "category": "GB"},
        {"code": "Wrexham", "category": "GB"},
        {"code": "York", "category": "GB"},
        {"code": "Alta Verapaz", "category": "GT"},
        {"code": "Baja Verapaz", "category": "GT"},
        {"code": "Chimaltenango", "category": "GT"},
        {"code": "Chiquimula", "category": "GT"},
        {"code": "El Progreso", "category": "GT"},
        {"code": "Escuintla", "category": "GT"},
        {"code": "Guatemala", "category": "GT"},
        {"code": "Huehuetenango", "category": "GT"},
        {"code": "Izabal", "category": "GT"},
        {"code": "Jalapa", "category": "GT"},
        {"code": "Jutiapa", "category": "GT"},
        {"code": "Petén", "category": "GT"},
        {"code": "Quetzaltenango", "category": "GT"},
        {"code": "Quiché", "category": "GT"},
        {"code": "Retalhuleu", "category": "GT"},
        {"code": "Sacatepéquez", "category": "GT"},
        {"code": "San Marcos", "category": "GT"},
        {"code": "Santa Rosa", "category": "GT"},
        {"code": "Sololá", "category": "GT"},
        {"code": "Suchitepéquez", "category": "GT"},
        {"code": "Totonicapán", "category": "GT"},
        {"code": "Zacapa", "category": "GT"},
        {"code": "New Territories", "category": "HK"},
        {"code": "Islands", "category": "HK"},
        {"code": "Kwai Tsing", "category": "HK"},
        {"code": "North", "category": "HK"},
        {"code": "Sai Kung", "category": "HK"},
        {"code": "Sha Tin", "category": "HK"},
        {"code": "Tai Po", "category": "HK"},
        {"code": "Tsuen Wan", "category": "HK"},
        {"code": "Tuen Mun", "category": "HK"},
        {"code": "Yuen Long", "category": "HK"},
        {"code": "Kowloon", "category": "HK"},
        {"code": "Sham Shui Po ", "category": "HK"},
        {"code": "Kowloon City ", "category": "HK"},
        {"code": "Kwun Tong ", "category": "HK"},
        {"code": "Wong Tai Sin ", "category": "HK"},
        {"code": "Yau Tsim Mong ", "category": "HK"},
        {"code": "Hong Kong Island ", "category": "HK"},
        {"code": "Central and Western", "category": "HK"},
        {"code": "Eastern", "category": "HK"},
        {"code": "Southern", "category": "HK"},
        {"code": "Wan Chai", "category": "HK"},
        {"code": "Budapest", "category": "HU"},
        {"code": "Bács-Kiskun", "category": "HU"},
        {"code": "Baranya", "category": "HU"},
        {"code": "Békés", "category": "HU"},
        {"code": "Borsod-Abaúj-Zemplén", "category": "HU"},
        {"code": "Csongrád", "category": "HU"},
        {"code": "Fejér", "category": "HU"},
        {"code": "Győr-Moson-Sopron", "category": "HU"},
        {"code": "Hajdú-Bihar", "category": "HU"},
        {"code": "Heves", "category": "HU"},
        {"code": "Jász-Nagykun-Szolnok", "category": "HU"},
        {"code": "Komárom-Esztergom", "category": "HU"},
        {"code": "Nógrád", "category": "HU"},
        {"code": "Pest", "category": "HU"},
        {"code": "Somogy", "category": "HU"},
        {"code": "Szabolcs-Szatmár-Bereg", "category": "HU"},
        {"code": "Tolna", "category": "HU"},
        {"code": "Vas", "category": "HU"},
        {"code": "Veszprém", "category": "HU"},
        {"code": "Zala", "category": "HU"},
        {"code": "Békéscsaba", "category": "HU"},
        {"code": "Debrecen", "category": "HU"},
        {"code": "Dunaújváros", "category": "HU"},
        {"code": "Eger", "category": "HU"},
        {"code": "Érd", "category": "HU"},
        {"code": "Győr", "category": "HU"},
        {"code": "Hódmezővásárhely", "category": "HU"},
        {"code": "Kaposvár", "category": "HU"},
        {"code": "Kecskemét", "category": "HU"},
        {"code": "Miskolc", "category": "HU"},
        {"code": "Nagykanizsa", "category": "HU"},
        {"code": "Nyíregyháza", "category": "HU"},
        {"code": "Pécs", "category": "HU"},
        {"code": "Salgótarján", "category": "HU"},
        {"code": "Sopron", "category": "HU"},
        {"code": "Szeged", "category": "HU"},
        {"code": "Székesfehérvár", "category": "HU"},
        {"code": "Szekszárd", "category": "HU"},
        {"code": "Szolnok", "category": "HU"},
        {"code": "Szombathely", "category": "HU"},
        {"code": "Tatabánya", "category": "HU"},
        {"code": "Zalaegerszeg", "category": "HU"},
        {"code": "Jawa", "category": "ID"},
        {"code": "Kalimantan", "category": "ID"},
        {"code": "Maluku", "category": "ID"},
        {"code": "Nusa Tenggara", "category": "ID"},
        {"code": "Papua", "category": "ID"},
        {"code": "Sulawesi", "category": "ID"},
        {"code": "Sumatera", "category": "ID"},
        {"code": "Aceh", "category": "ID"},
        {"code": "Bali", "category": "ID"},
        {"code": "Bangka Belitung", "category": "ID"},
        {"code": "Banten", "category": "ID"},
        {"code": "Bengkulu", "category": "ID"},
        {"code": "Gorontalo", "category": "ID"},
        {"code": "Jambi", "category": "ID"},
        {"code": "Jawa Barat", "category": "ID"},
        {"code": "Jawa Tengah", "category": "ID"},
        {"code": "Jawa Timur", "category": "ID"},
        {"code": "Kalimantan Barat", "category": "ID"},
        {"code": "Kalimantan Selatan", "category": "ID"},
        {"code": "Kalimantan Tengah", "category": "ID"},
        {"code": "Kalimantan Timur", "category": "ID"},
        {"code": "Kepulauan Riau", "category": "ID"},
        {"code": "Lampung", "category": "ID"},
        {"code": "Maluku Utara", "category": "ID"},
        {"code": "Nusa Tenggara Barat", "category": "ID"},
        {"code": "Nusa Tenggara Timur", "category": "ID"},
        {"code": "Papua Barat", "category": "ID"},
        {"code": "Riau", "category": "ID"},
        {"code": "Sulawesi Barat", "category": "ID"},
        {"code": "Sulawesi Selatan", "category": "ID"},
        {"code": "Sulawesi Tengah", "category": "ID"},
        {"code": "Sulawesi Tenggara", "category": "ID"},
        {"code": "Sulawesi Utara", "category": "ID"},
        {"code": "Sumatera Barat", "category": "ID"},
        {"code": "Sumatera Selatan", "category": "ID"},
        {"code": "Sumatera Utara", "category": "ID"},
        {"code": "Jakarta Raya", "category": "ID"},
        {"code": "Yogyakarta", "category": "ID"},
        {"code": "Carlow", "category": "IE"},
        {"code": "Cavan", "category": "IE"},
        {"code": "Clare", "category": "IE"},
        {"code": "Cork", "category": "IE"},
        {"code": "Donegal", "category": "IE"},
        {"code": "Dublin", "category": "IE"},
        {"code": "Dún Laoghaire–Rathdown", "category": "IE"},
        {"code": "Fingal", "category": "IE"},
        {"code": "Galway", "category": "IE"},
        {"code": "Kerry", "category": "IE"},
        {"code": "Kildare", "category": "IE"},
        {"code": "Kilkenny", "category": "IE"},
        {"code": "Laois", "category": "IE"},
        {"code": "Leitrim", "category": "IE"},
        {"code": "Limerick", "category": "IE"},
        {"code": "Longford", "category": "IE"},
        {"code": "Louth", "category": "IE"},
        {"code": "Mayo", "category": "IE"},
        {"code": "Meath", "category": "IE"},
        {"code": "Monaghan", "category": "IE"},
        {"code": "North Tipperary", "category": "IE"},
        {"code": "Offaly", "category": "IE"},
        {"code": "Roscommon", "category": "IE"},
        {"code": "Sligo", "category": "IE"},
        {"code": "South Dublin", "category": "IE"},
        {"code": "South Tipperary", "category": "IE"},
        {"code": "Tipperary", "category": "IE"},
        {"code": "Waterford", "category": "IE"},
        {"code": "Westmeath", "category": "IE"},
        {"code": "Wexford", "category": "IE"},
        {"code": "Wicklow", "category": "IE"},
        {"code": "Central", "category": "IL"},
        {"code": "Haifa", "category": "IL"},
        {"code": "Jerusalem", "category": "IL"},
        {"code": "Northern", "category": "IL"},
        {"code": "Southern", "category": "IL"},
        {"code": "Tel Aviv", "category": "IL"},
        {"code": "Andaman and Nicobar Islands", "category": "IN"},
        {"code": "Andhra Pradesh", "category": "IN"},
        {"code": "Arunachal Pradesh", "category": "IN"},
        {"code": "Assam", "category": "IN"},
        {"code": "Bihar", "category": "IN"},
        {"code": "Chandigarh Union territory", "category": "IN"},
        {"code": "Chhattisgarh", "category": "IN"},
        {"code": "Dadra and Nagar Haveli", "category": "IN"},
        {"code": "Daman and Diu", "category": "IN"},
        {"code": "Delhi", "category": "IN"},
        {"code": "Goa", "category": "IN"},
        {"code": "Gujarat", "category": "IN"},
        {"code": "Haryana", "category": "IN"},
        {"code": "Himachal Pradesh", "category": "IN"},
        {"code": "Jammu and Kashmir", "category": "IN"},
        {"code": "Jharkhand", "category": "IN"},
        {"code": "Karnataka", "category": "IN"},
        {"code": "Kerala", "category": "IN"},
        {"code": "Lakshadweep", "category": "IN"},
        {"code": "Madhya Pradesh", "category": "IN"},
        {"code": "Maharashtra", "category": "IN"},
        {"code": "Manipur", "category": "IN"},
        {"code": "Meghalaya", "category": "IN"},
        {"code": "Mizoram", "category": "IN"},
        {"code": "Nagaland", "category": "IN"},
        {"code": "Odisha", "category": "IN"},
        {"code": "Punjab", "category": "IN"},
        {"code": "PY Puducherry or Pondicherry", "category": "IN"},
        {"code": "Rajasthan", "category": "IN"},
        {"code": "Sikkim", "category": "IN"},
        {"code": "Tamil Nadu", "category": "IN"},
        {"code": "Telangana", "category": "IN"},
        {"code": "Tripura", "category": "IN"},
        {"code": "Uttarakhand", "category": "IN"},
        {"code": "Uttar Pradesh", "category": "IN"},
        {"code": "West Bengal", "category": "IN"},
        {"code": "Abruzzo", "category": "IT"},
        {"code": "Basilicata", "category": "IT"},
        {"code": "Calabria", "category": "IT"},
        {"code": "Campania", "category": "IT"},
        {"code": "Emilia-Romagna", "category": "IT"},
        {"code": "Friuli-Venezia Giulia", "category": "IT"},
        {"code": "Lazio", "category": "IT"},
        {"code": "Liguria", "category": "IT"},
        {"code": "Lombardia", "category": "IT"},
        {"code": "Marche", "category": "IT"},
        {"code": "Molise", "category": "IT"},
        {"code": "Piemonte", "category": "IT"},
        {"code": "Puglia", "category": "IT"},
        {"code": "Sardegna", "category": "IT"},
        {"code": "Sicilia", "category": "IT"},
        {"code": "Toscana", "category": "IT"},
        {"code": "Trentino-Alto Adige, Trentino-Südtirol (de)", "category": "IT"},
        {"code": "Umbria", "category": "IT"},
        {"code": "Valle d'Aosta, Vallée d'Aoste (fr)", "category": "IT"},
        {"code": "Veneto", "category": "IT"},
        {"code": "Agrigento", "category": "IT"},
        {"code": "Alessandria", "category": "IT"},
        {"code": "Ancona", "category": "IT"},
        {"code": "Aosta, Aoste (fr)", "category": "IT"},
        {"code": "Arezzo", "category": "IT"},
        {"code": "Ascoli Piceno", "category": "IT"},
        {"code": "Asti", "category": "IT"},
        {"code": "Avellino", "category": "IT"},
        {"code": "Bari", "category": "IT"},
        {"code": "Barletta-Andria-Trani", "category": "IT"},
        {"code": "Belluno", "category": "IT"},
        {"code": "Benevento", "category": "IT"},
        {"code": "Bergamo", "category": "IT"},
        {"code": "Biella", "category": "IT"},
        {"code": "Bologna", "category": "IT"},
        {"code": "Bolzano, Bozen (de)", "category": "IT"},
        {"code": "Brescia", "category": "IT"},
        {"code": "Brindisi", "category": "IT"},
        {"code": "Cagliari", "category": "IT"},
        {"code": "Caltanissetta", "category": "IT"},
        {"code": "Campobasso", "category": "IT"},
        {"code": "Carbonia-Iglesias", "category": "IT"},
        {"code": "Caserta", "category": "IT"},
        {"code": "Catania", "category": "IT"},
        {"code": "Catanzaro", "category": "IT"},
        {"code": "Chieti", "category": "IT"},
        {"code": "Como", "category": "IT"},
        {"code": "Cosenza", "category": "IT"},
        {"code": "Cremona", "category": "IT"},
        {"code": "Crotone", "category": "IT"},
        {"code": "Cuneo", "category": "IT"},
        {"code": "Enna", "category": "IT"},
        {"code": "Fermo", "category": "IT"},
        {"code": "Ferrara", "category": "IT"},
        {"code": "Firenze", "category": "IT"},
        {"code": "Foggia", "category": "IT"},
        {"code": "Forlì-Cesena", "category": "IT"},
        {"code": "Frosinone", "category": "IT"},
        {"code": "Genova", "category": "IT"},
        {"code": "Gorizia", "category": "IT"},
        {"code": "Grosseto", "category": "IT"},
        {"code": "Imperia", "category": "IT"},
        {"code": "Isernia", "category": "IT"},
        {"code": "La Spezia", "category": "IT"},
        {"code": "LAquila !L'Aquila", "category": "IT"},
        {"code": "Latina", "category": "IT"},
        {"code": "Lecce", "category": "IT"},
        {"code": "Lecco", "category": "IT"},
        {"code": "Livorno", "category": "IT"},
        {"code": "Lodi", "category": "IT"},
        {"code": "Lucca", "category": "IT"},
        {"code": "Macerata", "category": "IT"},
        {"code": "Mantova", "category": "IT"},
        {"code": "Massa-Carrara", "category": "IT"},
        {"code": "Matera", "category": "IT"},
        {"code": "Medio Campidano", "category": "IT"},
        {"code": "Messina", "category": "IT"},
        {"code": "Milano", "category": "IT"},
        {"code": "Modena", "category": "IT"},
        {"code": "Monza e Brianza", "category": "IT"},
        {"code": "Napoli", "category": "IT"},
        {"code": "Novara", "category": "IT"},
        {"code": "Nuoro", "category": "IT"},
        {"code": "Ogliastra", "category": "IT"},
        {"code": "Olbia-Tempio", "category": "IT"},
        {"code": "Oristano", "category": "IT"},
        {"code": "Padova", "category": "IT"},
        {"code": "Palermo", "category": "IT"},
        {"code": "Parma", "category": "IT"},
        {"code": "Pavia", "category": "IT"},
        {"code": "Perugia", "category": "IT"},
        {"code": "Pesaro e Urbino", "category": "IT"},
        {"code": "Pescara", "category": "IT"},
        {"code": "Piacenza", "category": "IT"},
        {"code": "Pisa", "category": "IT"},
        {"code": "Pistoia", "category": "IT"},
        {"code": "Pordenone", "category": "IT"},
        {"code": "Potenza", "category": "IT"},
        {"code": "Prato", "category": "IT"},
        {"code": "Ragusa", "category": "IT"},
        {"code": "Ravenna", "category": "IT"},
        {"code": "Reggio Calabria", "category": "IT"},
        {"code": "Reggio Emilia", "category": "IT"},
        {"code": "Rieti", "category": "IT"},
        {"code": "Rimini", "category": "IT"},
        {"code": "Roma", "category": "IT"},
        {"code": "Rovigo", "category": "IT"},
        {"code": "Salerno", "category": "IT"},
        {"code": "Sassari", "category": "IT"},
        {"code": "Savona", "category": "IT"},
        {"code": "Siena", "category": "IT"},
        {"code": "Siracusa", "category": "IT"},
        {"code": "Sondrio", "category": "IT"},
        {"code": "Taranto", "category": "IT"},
        {"code": "Teramo", "category": "IT"},
        {"code": "Terni", "category": "IT"},
        {"code": "Torino", "category": "IT"},
        {"code": "Trapani", "category": "IT"},
        {"code": "Trento", "category": "IT"},
        {"code": "Treviso", "category": "IT"},
        {"code": "Trieste", "category": "IT"},
        {"code": "Udine", "category": "IT"},
        {"code": "Varese", "category": "IT"},
        {"code": "Venezia", "category": "IT"},
        {"code": "Verbano-Cusio-Ossola", "category": "IT"},
        {"code": "Vercelli", "category": "IT"},
        {"code": "Verona", "category": "IT"},
        {"code": "Vibo Valentia", "category": "IT"},
        {"code": "Vicenza", "category": "IT"},
        {"code": "Viterbo", "category": "IT"},
        {"code": "Aiti ", "category": "JP"},
        {"code": "Akita", "category": "JP"},
        {"code": "Aomori", "category": "JP"},
        {"code": "Ehime", "category": "JP"},
        {"code": "Gihu ", "category": "JP"},
        {"code": "Gunma", "category": "JP"},
        {"code": "Hirosima", "category": "JP"},
        {"code": "Hokkaidô", "category": "JP"},
        {"code": "Hukui", "category": "JP"},
        {"code": "Hukuoka", "category": "JP"},
        {"code": "Hukusima", "category": "JP"},
        {"code": "Hyôgo", "category": "JP"},
        {"code": "Ibaraki", "category": "JP"},
        {"code": "Isikawa", "category": "JP"},
        {"code": "Iwate", "category": "JP"},
        {"code": "Kagawa", "category": "JP"},
        {"code": "Kagosima", "category": "JP"},
        {"code": "Kanagawa", "category": "JP"},
        {"code": "Kôti", "category": "JP"},
        {"code": "Kumamoto", "category": "JP"},
        {"code": "Kyôto", "category": "JP"},
        {"code": "Mie", "category": "JP"},
        {"code": "Miyagi", "category": "JP"},
        {"code": "Miyazaki", "category": "JP"},
        {"code": "Nagano", "category": "JP"},
        {"code": "Nagasaki", "category": "JP"},
        {"code": "Nara", "category": "JP"},
        {"code": "Niigata", "category": "JP"},
        {"code": "Ôita", "category": "JP"},
        {"code": "Okayama", "category": "JP"},
        {"code": "Okinawa", "category": "JP"},
        {"code": "Ôsaka", "category": "JP"},
        {"code": "Saga", "category": "JP"},
        {"code": "Saitama", "category": "JP"},
        {"code": "Siga", "category": "JP"},
        {"code": "Simane", "category": "JP"},
        {"code": "Sizuoka", "category": "JP"},
        {"code": "Tiba", "category": "JP"},
        {"code": "Totigi", "category": "JP"},
        {"code": "Tokusima", "category": "JP"},
        {"code": "Tôkyô", "category": "JP"},
        {"code": "Tottori", "category": "JP"},
        {"code": "Toyama", "category": "JP"},
        {"code": "Wakayama", "category": "JP"},
        {"code": "Yamagata", "category": "JP"},
        {"code": "Yamaguti", "category": "JP"},
        {"code": "Yamanasi", "category": "JP"},
        {"code": "Seoul", "category": "KR"},
        {"code": "Busan", "category": "KR"},
        {"code": "Daegu", "category": "KR"},
        {"code": "Daejeon", "category": "KR"},
        {"code": "Gwangju", "category": "KR"},
        {"code": "Incheon", "category": "KR"},
        {"code": "Ulsan", "category": "KR"},
        {"code": "North Chungcheong", "category": "KR"},
        {"code": "South Chungcheong", "category": "KR"},
        {"code": "Gangwon", "category": "KR"},
        {"code": "Gyeonggi", "category": "KR"},
        {"code": "North Gyeongsang", "category": "KR"},
        {"code": "South Gyeongsang", "category": "KR"},
        {"code": "Jeju", "category": "KR"},
        {"code": "North Jeolla", "category": "KR"},
        {"code": "South Jeolla", "category": "KR"},
        {"code": "Almaty", "category": "KZ"},
        {"code": "Astana", "category": "KZ"},
        {"code": "Almaty oblysy", "category": "KZ"},
        {"code": "Aqmola oblysy", "category": "KZ"},
        {"code": "Aqtöbe oblysy", "category": "KZ"},
        {"code": "Atyraū oblysy", "category": "KZ"},
        {"code": "Batys Qazaqstan oblysy", "category": "KZ"},
        {"code": "Mangghystaū oblysy", "category": "KZ"},
        {"code": "Ongtüstik Qazaqstan oblysy", "category": "KZ"},
        {"code": "Pavlodar oblysy", "category": "KZ"},
        {"code": "Qaraghandy oblysy", "category": "KZ"},
        {"code": "Qostanay oblysy", "category": "KZ"},
        {"code": "Qyzylorda oblysy", "category": "KZ"},
        {"code": "Shyghys Qazaqstan oblysy", "category": "KZ"},
        {"code": "Soltüstik Qazaqstan oblysy", "category": "KZ"},
        {"code": "Zhambyl oblysy", "category": "KZ"},
        {"code": "Aakkâr", "category": "LB"},
        {"code": "Baalbek-Hermel", "category": "LB"},
        {"code": "Béqaa", "category": "LB"},
        {"code": "Beyrouth", "category": "LB"},
        {"code": "Liban-Nord", "category": "LB"},
        {"code": "Liban-Sud", "category": "LB"},
        {"code": "Mont-Liban", "category": "LB"},
        {"code": "Nabatîyé", "category": "LB"},
        {"code": "Anse-la-Raye", "category": "LC"},
        {"code": "Canaries", "category": "LC"},
        {"code": "Castries", "category": "LC"},
        {"code": "Choiseul", "category": "LC"},
        {"code": "Dennery", "category": "LC"},
        {"code": "Gros Islet", "category": "LC"},
        {"code": "Laborie", "category": "LC"},
        {"code": "Micoud", "category": "LC"},
        {"code": "Soufriere", "category": "LC"},
        {"code": "Vieux Fort", "category": "LC"},
        {"code": "Alytaus Apskritis", "category": "LT"},
        {"code": "Kauno Apskritis", "category": "LT"},
        {"code": "Klaipėdos Apskritis", "category": "LT"},
        {"code": "Marijampolės Apskritis", "category": "LT"},
        {"code": "Panevėžio Apskritis", "category": "LT"},
        {"code": "Šiaulių Apskritis", "category": "LT"},
        {"code": "Tauragės Apskritis", "category": "LT"},
        {"code": "Telšių Apskritis", "category": "LT"},
        {"code": "Utenos Apskritis", "category": "LT"},
        {"code": "Vilniaus Apskritis", "category": "LT"},
        {"code": "Diekirch", "category": "LU"},
        {"code": "Grevenmacher", "category": "LU"},
        {"code": "Luxembourg", "category": "LU"},
        {"code": "Aguascalientes", "category": "MX"},
        {"code": "Baja California", "category": "MX"},
        {"code": "Baja California Sur", "category": "MX"},
        {"code": "Campeche", "category": "MX"},
        {"code": "Chiapas", "category": "MX"},
        {"code": "Chihuahua", "category": "MX"},
        {"code": "Ciudad de México", "category": "MX"},
        {"code": "Coahuila de Zaragoza", "category": "MX"},
        {"code": "Colima", "category": "MX"},
        {"code": "Durango", "category": "MX"},
        {"code": "Guanajuato", "category": "MX"},
        {"code": "Guerrero", "category": "MX"},
        {"code": "Hidalgo", "category": "MX"},
        {"code": "Jalisco", "category": "MX"},
        {"code": "México", "category": "MX"},
        {"code": "Michoacán de Ocampo", "category": "MX"},
        {"code": "Morelos", "category": "MX"},
        {"code": "Nayarit", "category": "MX"},
        {"code": "Nuevo León", "category": "MX"},
        {"code": "Oaxaca", "category": "MX"},
        {"code": "Puebla", "category": "MX"},
        {"code": "Querétaro de Arteaga", "category": "MX"},
        {"code": "Quintana Roo", "category": "MX"},
        {"code": "San Luis Potosí", "category": "MX"},
        {"code": "Sinaloa", "category": "MX"},
        {"code": "Sonora", "category": "MX"},
        {"code": "Tabasco", "category": "MX"},
        {"code": "Tamaulipas", "category": "MX"},
        {"code": "Tlaxcala", "category": "MX"},
        {"code": "Veracruz de Ignacio de la Llave", "category": "MX"},
        {"code": "Yucatán", "category": "MX"},
        {"code": "Zacatecas", "category": "MX"},
        {"code": "Wilayah Persekutuan Kuala Lumpur", "category": "MY"},
        {"code": "Wilayah Persekutuan Labuan", "category": "MY"},
        {"code": "Wilayah Persekutuan Putrajaya", "category": "MY"},
        {"code": "Johor", "category": "MY"},
        {"code": "Kedah", "category": "MY"},
        {"code": "Kelantan", "category": "MY"},
        {"code": "Melaka", "category": "MY"},
        {"code": "Negeri Sembilan", "category": "MY"},
        {"code": "Pahang", "category": "MY"},
        {"code": "Perak", "category": "MY"},
        {"code": "Perlis", "category": "MY"},
        {"code": "Pulau Pinang", "category": "MY"},
        {"code": "Sabah", "category": "MY"},
        {"code": "Sarawak", "category": "MY"},
        {"code": "Selangor", "category": "MY"},
        {"code": "Terengganu", "category": "MY"},
        {"code": "Drenthe", "category": "NL"},
        {"code": "Flevoland", "category": "NL"},
        {"code": "Fryslân (fy)", "category": "NL"},
        {"code": "Gelderland", "category": "NL"},
        {"code": "Groningen", "category": "NL"},
        {"code": "Limburg", "category": "NL"},
        {"code": "Noord-Brabant", "category": "NL"},
        {"code": "Noord-Holland", "category": "NL"},
        {"code": "Overijssel", "category": "NL"},
        {"code": "Utrecht", "category": "NL"},
        {"code": "Zeeland", "category": "NL"},
        {"code": "Zuid-Holland", "category": "NL"},
        {"code": "Aruba", "category": "NL"},
        {"code": "Curaçao", "category": "NL"},
        {"code": "Sint Maarten", "category": "NL"},
        {"code": "Bonaire", "category": "NL"},
        {"code": "Saba", "category": "NL"},
        {"code": "Sint Eustatius", "category": "NL"},
        {"code": "Akershus", "category": "NO"},
        {"code": "Aust-Agder", "category": "NO"},
        {"code": "Buskerud", "category": "NO"},
        {"code": "Finnmark", "category": "NO"},
        {"code": "Hedmark", "category": "NO"},
        {"code": "Hordaland", "category": "NO"},
        {"code": "Møre og Romsdal", "category": "NO"},
        {"code": "Nordland", "category": "NO"},
        {"code": "Nord-Trøndelag", "category": "NO"},
        {"code": "Oppland", "category": "NO"},
        {"code": "Oslo", "category": "NO"},
        {"code": "Rogaland", "category": "NO"},
        {"code": "Sogn og Fjordane", "category": "NO"},
        {"code": "Sør-Trøndelag", "category": "NO"},
        {"code": "Telemark", "category": "NO"},
        {"code": "Troms", "category": "NO"},
        {"code": "Vest-Agder", "category": "NO"},
        {"code": "Vestfold", "category": "NO"},
        {"code": "Østfold", "category": "NO"},
        {"code": "Jan Mayen", "category": "NO"},
        {"code": "Svalbard", "category": "NO"},
        {"code": "North Island", "category": "NZ"},
        {"code": "South Island", "category": "NZ"},
        {"code": "Auckland", "category": "NZ"},
        {"code": "Bay of Plenty", "category": "NZ"},
        {"code": "Canterbury", "category": "NZ"},
        {"code": "Hawke's Bay", "category": "NZ"},
        {"code": "Manawatu-Wanganui", "category": "NZ"},
        {"code": "Northland", "category": "NZ"},
        {"code": "Otago", "category": "NZ"},
        {"code": "Southland", "category": "NZ"},
        {"code": "Taranaki", "category": "NZ"},
        {"code": "Waikato", "category": "NZ"},
        {"code": "Wellington", "category": "NZ"},
        {"code": "West Coast", "category": "NZ"},
        {"code": "Gisborne District", "category": "NZ"},
        {"code": "Marlborough District", "category": "NZ"},
        {"code": "Nelson City", "category": "NZ"},
        {"code": "Tasman District", "category": "NZ"},
        {"code": "Chatham Islands Territory", "category": "NZ"},
        {"code": "El Callao", "category": "PE"},
        {"code": "Municipalidad Metropolitana de Lima", "category": "PE"},
        {"code": "Amazonas", "category": "PE"},
        {"code": "Ancash", "category": "PE"},
        {"code": "Apurímac", "category": "PE"},
        {"code": "Arequipa", "category": "PE"},
        {"code": "Ayacucho", "category": "PE"},
        {"code": "Cajamarca", "category": "PE"},
        {"code": "Cusco [Cuzco]", "category": "PE"},
        {"code": "Huancavelica", "category": "PE"},
        {"code": "Huánuco", "category": "PE"},
        {"code": "Ica", "category": "PE"},
        {"code": "Junín", "category": "PE"},
        {"code": "La Libertad", "category": "PE"},
        {"code": "Lambayeque", "category": "PE"},
        {"code": "Lima", "category": "PE"},
        {"code": "Loreto", "category": "PE"},
        {"code": "Madre de Dios", "category": "PE"},
        {"code": "Moquegua", "category": "PE"},
        {"code": "Pasco", "category": "PE"},
        {"code": "Piura", "category": "PE"},
        {"code": "Puno", "category": "PE"},
        {"code": "San Martín", "category": "PE"},
        {"code": "Tacna", "category": "PE"},
        {"code": "Tumbes", "category": "PE"},
        {"code": "Ucayali", "category": "PE"},
        {"code": "Autonomous Region in Muslim Mindanao (ARMM)", "category": "PH"},
        {"code": "Bicol (Region V)", "category": "PH"},
        {"code": "Cagayan Valley (Region II)", "category": "PH"},
        {"code": "CALABARZON (Region IV-A)", "category": "PH"},
        {"code": "Caraga (Region XIII)", "category": "PH"},
        {"code": "Central Luzon (Region III)", "category": "PH"},
        {"code": "Central Visayas (Region VII)", "category": "PH"},
        {"code": "Cordillera Administrative Region (CAR)", "category": "PH"},
        {"code": "Davao (Region XI)", "category": "PH"},
        {"code": "Eastern Visayas (Region VIII)", "category": "PH"},
        {"code": "Ilocos (Region I)", "category": "PH"},
        {"code": "MIMAROPA (Region IV-B)", "category": "PH"},
        {"code": "National Capital Region", "category": "PH"},
        {"code": "Northern Mindanao (Region X)", "category": "PH"},
        {"code": "Soccsksargen (Region XII)", "category": "PH"},
        {"code": "Western Visayas (Region VI)", "category": "PH"},
        {"code": "Zamboanga Peninsula (Region IX)", "category": "PH"},
        {"code": "Abra", "category": "PH"},
        {"code": "Agusan del Norte", "category": "PH"},
        {"code": "Agusan del Sur", "category": "PH"},
        {"code": "Aklan", "category": "PH"},
        {"code": "Albay", "category": "PH"},
        {"code": "Antique", "category": "PH"},
        {"code": "Apayao", "category": "PH"},
        {"code": "Aurora", "category": "PH"},
        {"code": "Basilan", "category": "PH"},
        {"code": "Bataan", "category": "PH"},
        {"code": "Batanes", "category": "PH"},
        {"code": "Batangas", "category": "PH"},
        {"code": "Benguet", "category": "PH"},
        {"code": "Biliran", "category": "PH"},
        {"code": "Bohol", "category": "PH"},
        {"code": "Bukidnon", "category": "PH"},
        {"code": "Bulacan", "category": "PH"},
        {"code": "Cagayan", "category": "PH"},
        {"code": "Camarines Norte", "category": "PH"},
        {"code": "Camarines Sur", "category": "PH"},
        {"code": "Camiguin", "category": "PH"},
        {"code": "Capiz", "category": "PH"},
        {"code": "Catanduanes", "category": "PH"},
        {"code": "Cavite", "category": "PH"},
        {"code": "Cebu", "category": "PH"},
        {"code": "Compostela Valley", "category": "PH"},
        {"code": "Cotabato", "category": "PH"},
        {"code": "Davao del Norte", "category": "PH"},
        {"code": "Davao del Sur", "category": "PH"},
        {"code": "Davao Oriental", "category": "PH"},
        {"code": "Dinagat Islands", "category": "PH"},
        {"code": "Eastern Samar", "category": "PH"},
        {"code": "Guimaras", "category": "PH"},
        {"code": "Ifugao", "category": "PH"},
        {"code": "Ilocos Norte", "category": "PH"},
        {"code": "Ilocos Sur", "category": "PH"},
        {"code": "Iloilo", "category": "PH"},
        {"code": "Isabela", "category": "PH"},
        {"code": "Kalinga", "category": "PH"},
        {"code": "La Union", "category": "PH"},
        {"code": "Laguna", "category": "PH"},
        {"code": "Lanao del Norte", "category": "PH"},
        {"code": "Lanao del Sur", "category": "PH"},
        {"code": "Leyte", "category": "PH"},
        {"code": "Maguindanao", "category": "PH"},
        {"code": "Marinduque", "category": "PH"},
        {"code": "Masbate", "category": "PH"},
        {"code": "Mindoro Occidental", "category": "PH"},
        {"code": "Mindoro Oriental", "category": "PH"},
        {"code": "Misamis Occidental", "category": "PH"},
        {"code": "Misamis Oriental", "category": "PH"},
        {"code": "Mountain Province", "category": "PH"},
        {"code": "Negros Occidental", "category": "PH"},
        {"code": "Negros Oriental", "category": "PH"},
        {"code": "Northern Samar", "category": "PH"},
        {"code": "Nueva Ecija", "category": "PH"},
        {"code": "Nueva Vizcaya", "category": "PH"},
        {"code": "Palawan", "category": "PH"},
        {"code": "Pampanga", "category": "PH"},
        {"code": "Pangasinan", "category": "PH"},
        {"code": "Quezon", "category": "PH"},
        {"code": "Quirino", "category": "PH"},
        {"code": "Rizal", "category": "PH"},
        {"code": "Romblon", "category": "PH"},
        {"code": "Samar (Western Samar)", "category": "PH"},
        {"code": "Sarangani", "category": "PH"},
        {"code": "Siquijor", "category": "PH"},
        {"code": "Sorsogon", "category": "PH"},
        {"code": "South Cotabato", "category": "PH"},
        {"code": "Southern Leyte", "category": "PH"},
        {"code": "Sultan Kudarat", "category": "PH"},
        {"code": "Sulu", "category": "PH"},
        {"code": "Surigao del Norte", "category": "PH"},
        {"code": "Surigao del Sur", "category": "PH"},
        {"code": "Tarlac", "category": "PH"},
        {"code": "Tawi-Tawi", "category": "PH"},
        {"code": "Zambales", "category": "PH"},
        {"code": "Zamboanga del Norte", "category": "PH"},
        {"code": "Zamboanga del Sur", "category": "PH"},
        {"code": "Zamboanga Sibugay", "category": "PH"},
        {"code": "Dolnośląskie", "category": "PL"},
        {"code": "Kujawsko-pomorskie", "category": "PL"},
        {"code": "Lubelskie", "category": "PL"},
        {"code": "Lubuskie", "category": "PL"},
        {"code": "Łódzkie", "category": "PL"},
        {"code": "Ma��opolskie", "category": "PL"},
        {"code": "Mazowieckie", "category": "PL"},
        {"code": "Opolskie", "category": "PL"},
        {"code": "Podkarpackie", "category": "PL"},
        {"code": "Podlaskie", "category": "PL"},
        {"code": "Pomorskie", "category": "PL"},
        {"code": "Śląskie", "category": "PL"},
        {"code": "Świętokrzyskie", "category": "PL"},
        {"code": "Warmińsko-mazurskie", "category": "PL"},
        {"code": "Wielkopolskie", "category": "PL"},
        {"code": "Zachodniopomorskie", "category": "PL"},
        {"code": "Aveiro", "category": "PT"},
        {"code": "Beja", "category": "PT"},
        {"code": "Braga", "category": "PT"},
        {"code": "Bragança", "category": "PT"},
        {"code": "Castelo Branco", "category": "PT"},
        {"code": "Coimbra", "category": "PT"},
        {"code": "Évora", "category": "PT"},
        {"code": "Faro", "category": "PT"},
        {"code": "Guarda", "category": "PT"},
        {"code": "Leiria", "category": "PT"},
        {"code": "Lisboa", "category": "PT"},
        {"code": "Portalegre", "category": "PT"},
        {"code": "Porto", "category": "PT"},
        {"code": "Santarém", "category": "PT"},
        {"code": "Setúbal", "category": "PT"},
        {"code": "Viana do Castelo", "category": "PT"},
        {"code": "Vila Real", "category": "PT"},
        {"code": "Viseu", "category": "PT"},
        {"code": "Região Autónoma dos Açores", "category": "PT"},
        {"code": "Região Autónoma da Madeira", "category": "PT"},
        {"code": "Adygeya, Respublika", "category": "RU"},
        {"code": "Altay, Respublika", "category": "RU"},
        {"code": "Bashkortostan, Respublika", "category": "RU"},
        {"code": "Buryatiya, Respublika", "category": "RU"},
        {"code": "Chechenskaya Respublika", "category": "RU"},
        {"code": "Chuvashskaya Respublika", "category": "RU"},
        {"code": "Dagestan, Respublika", "category": "RU"},
        {"code": "Ingushetiya, Respublika", "category": "RU"},
        {"code": "Kabardino-Balkarskaya Respublika", "category": "RU"},
        {"code": "Kalmykiya, Respublika", "category": "RU"},
        {"code": "Karachayevo-Cherkesskaya Respublika", "category": "RU"},
        {"code": "Kareliya, Respublika", "category": "RU"},
        {"code": "Khakasiya, Respublika", "category": "RU"},
        {"code": "Komi, Respublika", "category": "RU"},
        {"code": "Mariy El, Respublika", "category": "RU"},
        {"code": "Mordoviya, Respublika", "category": "RU"},
        {"code": "Sakha, Respublika [Yakutiya]", "category": "RU"},
        {"code": "Severnaya Osetiya-Alaniya, Respublika", "category": "RU"},
        {"code": "Tatarstan, Respublika", "category": "RU"},
        {"code": "Tyva, Respublika [Tuva]", "category": "RU"},
        {"code": "Udmurtskaya Respublika", "category": "RU"},
        {"code": "Altayskiy kray", "category": "RU"},
        {"code": "Kamchatskiy kray", "category": "RU"},
        {"code": "Khabarovskiy kray", "category": "RU"},
        {"code": "Krasnodarskiy kray", "category": "RU"},
        {"code": "Krasnoyarskiy kray", "category": "RU"},
        {"code": "Permskiy kray", "category": "RU"},
        {"code": "Primorskiy kray", "category": "RU"},
        {"code": "Stavropol'skiy kray", "category": "RU"},
        {"code": "Zabaykal'skiy kray", "category": "RU"},
        {"code": "Amurskaya oblast'", "category": "RU"},
        {"code": "Arkhangel'skaya oblast'", "category": "RU"},
        {"code": "Astrakhanskaya oblast'", "category": "RU"},
        {"code": "Belgorodskaya oblast'", "category": "RU"},
        {"code": "Bryanskaya oblast'", "category": "RU"},
        {"code": "Chelyabinskaya oblast'", "category": "RU"},
        {"code": "Irkutskaya oblast'", "category": "RU"},
        {"code": "Ivanovskaya oblast'", "category": "RU"},
        {"code": "Kaliningradskaya oblast'", "category": "RU"},
        {"code": "Kaluzhskaya oblast'", "category": "RU"},
        {"code": "Kemerovskaya oblast'", "category": "RU"},
        {"code": "Kirovskaya oblast'", "category": "RU"},
        {"code": "Kostromskaya oblast'", "category": "RU"},
        {"code": "Kurganskaya oblast'", "category": "RU"},
        {"code": "Kurskaya oblast'", "category": "RU"},
        {"code": "Leningradskaya oblast'", "category": "RU"},
        {"code": "Lipetskaya oblast'", "category": "RU"},
        {"code": "Magadanskaya oblast'", "category": "RU"},
        {"code": "Moskovskaya oblast'", "category": "RU"},
        {"code": "Murmanskaya oblast'", "category": "RU"},
        {"code": "Nizhegorodskaya oblast'", "category": "RU"},
        {"code": "Novgorodskaya oblast'", "category": "RU"},
        {"code": "Novosibirskaya oblast'", "category": "RU"},
        {"code": "Omskaya oblast'", "category": "RU"},
        {"code": "Orenburgskaya oblast'", "category": "RU"},
        {"code": "Orlovskaya oblast'", "category": "RU"},
        {"code": "Penzenskaya oblast'", "category": "RU"},
        {"code": "Pskovskaya oblast'", "category": "RU"},
        {"code": "Rostovskaya oblast'", "category": "RU"},
        {"code": "Ryazanskaya oblast'", "category": "RU"},
        {"code": "Sakhalinskaya oblast'", "category": "RU"},
        {"code": "Samarskaya oblast'", "category": "RU"},
        {"code": "Saratovskaya oblast'", "category": "RU"},
        {"code": "Smolenskaya oblast'", "category": "RU"},
        {"code": "Sverdlovskaya oblast'", "category": "RU"},
        {"code": "Tambovskaya oblast'", "category": "RU"},
        {"code": "Tomskaya oblast'", "category": "RU"},
        {"code": "Tul'skaya oblast'", "category": "RU"},
        {"code": "Tverskaya oblast'", "category": "RU"},
        {"code": "Tyumenskaya oblast'", "category": "RU"},
        {"code": "Ul'yanovskaya oblast'", "category": "RU"},
        {"code": "Vladimirskaya oblast'", "category": "RU"},
        {"code": "Volgogradskaya oblast'", "category": "RU"},
        {"code": "Vologodskaya oblast'", "category": "RU"},
        {"code": "Voronezhskaya oblast'", "category": "RU"},
        {"code": "Yaroslavskaya oblast'", "category": "RU"},
        {"code": "Moskva", "category": "RU"},
        {"code": "Sankt-Peterburg", "category": "RU"},
        {"code": "Yevreyskaya avtonomnaya oblast'", "category": "RU"},
        {"code": "Chukotskiy avtonomnyy okrug", "category": "RU"},
        {"code": "Khanty-Mansiyskiy avtonomnyy okrug-Yugra", "category": "RU"},
        {"code": "Nenetskiy avtonomnyy okrug", "category": "RU"},
        {"code": "Yamalo-Nenetskiy avtonomnyy okrug", "category": "RU"},
        {"code": "Blekinge län", "category": "SE"},
        {"code": "Dalarnas län", "category": "SE"},
        {"code": "Gotlands län", "category": "SE"},
        {"code": "Gävleborgs län", "category": "SE"},
        {"code": "Hallands län", "category": "SE"},
        {"code": "Jämtlands län", "category": "SE"},
        {"code": "Jönköpings län", "category": "SE"},
        {"code": "Kalmar län", "category": "SE"},
        {"code": "Kronobergs län", "category": "SE"},
        {"code": "Norrbottens län", "category": "SE"},
        {"code": "Skåne län", "category": "SE"},
        {"code": "Stockholms län", "category": "SE"},
        {"code": "Södermanlands län", "category": "SE"},
        {"code": "Uppsala län", "category": "SE"},
        {"code": "Värmlands län", "category": "SE"},
        {"code": "Västerbottens län", "category": "SE"},
        {"code": "Västernorrlands län", "category": "SE"},
        {"code": "Västmanlands län", "category": "SE"},
        {"code": "Västra Götalands län", "category": "SE"},
        {"code": "Örebro län", "category": "SE"},
        {"code": "Östergötlands län", "category": "SE"},
        {"code": "Central Singapore", "category": "SG"},
        {"code": "North East", "category": "SG"},
        {"code": "North West", "category": "SG"},
        {"code": "South East", "category": "SG"},
        {"code": "South West", "category": "SG"},
        {"code": "Banskobystrický kraj", "category": "SK"},
        {"code": "Bratislavský kraj", "category": "SK"},
        {"code": "Košický kraj", "category": "SK"},
        {"code": "Nitriansky kraj", "category": "SK"},
        {"code": "Prešovský kraj", "category": "SK"},
        {"code": "Trenčiansky kraj", "category": "SK"},
        {"code": "Trnavský kraj", "category": "SK"},
        {"code": "Žilinský kraj", "category": "SK"},
        {"code": "Ahuachapán", "category": "SV"},
        {"code": "Cabañas", "category": "SV"},
        {"code": "Cuscatlán", "category": "SV"},
        {"code": "Chalatenango", "category": "SV"},
        {"code": "La Libertad", "category": "SV"},
        {"code": "La Paz", "category": "SV"},
        {"code": "La Unión", "category": "SV"},
        {"code": "Morazán", "category": "SV"},
        {"code": "San Miguel", "category": "SV"},
        {"code": "San Salvador", "category": "SV"},
        {"code": "Santa Ana", "category": "SV"},
        {"code": "San Vicente", "category": "SV"},
        {"code": "Sonsonate", "category": "SV"},
        {"code": "Usulután", "category": "SV"},
        {"code": "Krung Thep Maha Nakhon [Bangkok]", "category": "TH"},
        {"code": "Phatthaya", "category": "TH"},
        {"code": "Amnat Charoen", "category": "TH"},
        {"code": "Ang Thong", "category": "TH"},
        {"code": "Bueng Kan", "category": "TH"},
        {"code": "Buri Ram", "category": "TH"},
        {"code": "Chachoengsao", "category": "TH"},
        {"code": "Chai Nat", "category": "TH"},
        {"code": "Chaiyaphum", "category": "TH"},
        {"code": "Chanthaburi", "category": "TH"},
        {"code": "Chiang Mai", "category": "TH"},
        {"code": "Chiang Rai", "category": "TH"},
        {"code": "Chon Buri", "category": "TH"},
        {"code": "Chumphon", "category": "TH"},
        {"code": "Kalasin", "category": "TH"},
        {"code": "Kamphaeng Phet", "category": "TH"},
        {"code": "Kanchanaburi", "category": "TH"},
        {"code": "Khon Kaen", "category": "TH"},
        {"code": "Krabi", "category": "TH"},
        {"code": "Lampang", "category": "TH"},
        {"code": "Lamphun", "category": "TH"},
        {"code": "Loei", "category": "TH"},
        {"code": "Lop Buri", "category": "TH"},
        {"code": "Mae Hong Son", "category": "TH"},
        {"code": "Maha Sarakham", "category": "TH"},
        {"code": "Mukdahan", "category": "TH"},
        {"code": "Nakhon Nayok", "category": "TH"},
        {"code": "Nakhon Pathom", "category": "TH"},
        {"code": "Nakhon Phanom", "category": "TH"},
        {"code": "Nakhon Ratchasima", "category": "TH"},
        {"code": "Nakhon Sawan", "category": "TH"},
        {"code": "Nakhon Si Thammarat", "category": "TH"},
        {"code": "Nan", "category": "TH"},
        {"code": "Narathiwat", "category": "TH"},
        {"code": "Nong Bua Lam Phu", "category": "TH"},
        {"code": "Nong Khai", "category": "TH"},
        {"code": "Nonthaburi", "category": "TH"},
        {"code": "Pathum Thani", "category": "TH"},
        {"code": "Pattani", "category": "TH"},
        {"code": "Phangnga", "category": "TH"},
        {"code": "Phatthalung", "category": "TH"},
        {"code": "Phayao", "category": "TH"},
        {"code": "Phetchabun", "category": "TH"},
        {"code": "Phetchaburi", "category": "TH"},
        {"code": "Phichit", "category": "TH"},
        {"code": "Phitsanulok", "category": "TH"},
        {"code": "Phrae", "category": "TH"},
        {"code": "Phra Nakhon Si Ayutthaya", "category": "TH"},
        {"code": "Phuket", "category": "TH"},
        {"code": "Prachin Buri", "category": "TH"},
        {"code": "Prachuap Khiri Khan", "category": "TH"},
        {"code": "Ranong", "category": "TH"},
        {"code": "Ratchaburi", "category": "TH"},
        {"code": "Rayong", "category": "TH"},
        {"code": "Roi Et", "category": "TH"},
        {"code": "Sa Kaeo", "category": "TH"},
        {"code": "Sakon Nakhon", "category": "TH"},
        {"code": "Samut Prakan", "category": "TH"},
        {"code": "Samut Sakhon", "category": "TH"},
        {"code": "Samut Songkhram", "category": "TH"},
        {"code": "Saraburi", "category": "TH"},
        {"code": "Satun", "category": "TH"},
        {"code": "Sing Buri", "category": "TH"},
        {"code": "Si Sa Ket", "category": "TH"},
        {"code": "Songkhla", "category": "TH"},
        {"code": "Sukhothai", "category": "TH"},
        {"code": "Suphan Buri", "category": "TH"},
        {"code": "Surat Thani", "category": "TH"},
        {"code": "Surin", "category": "TH"},
        {"code": "Tak", "category": "TH"},
        {"code": "Trang", "category": "TH"},
        {"code": "Trat", "category": "TH"},
        {"code": "Ubon Ratchathani", "category": "TH"},
        {"code": "Udon Thani", "category": "TH"},
        {"code": "Uthai Thani", "category": "TH"},
        {"code": "Uttaradit", "category": "TH"},
        {"code": "Yala", "category": "TH"},
        {"code": "Yasothon", "category": "TH"},
        {"code": "Adana", "category": "TR"},
        {"code": "Adıyaman", "category": "TR"},
        {"code": "Afyonkarahisar", "category": "TR"},
        {"code": "Ağrı", "category": "TR"},
        {"code": "Aksaray", "category": "TR"},
        {"code": "Amasya", "category": "TR"},
        {"code": "Ankara", "category": "TR"},
        {"code": "Antalya", "category": "TR"},
        {"code": "Ardahan", "category": "TR"},
        {"code": "Artvin", "category": "TR"},
        {"code": "Aydın", "category": "TR"},
        {"code": "Balıkesir", "category": "TR"},
        {"code": "Bartın", "category": "TR"},
        {"code": "Batman", "category": "TR"},
        {"code": "Bayburt", "category": "TR"},
        {"code": "Bilecik", "category": "TR"},
        {"code": "Bingöl", "category": "TR"},
        {"code": "Bitlis", "category": "TR"},
        {"code": "Bolu", "category": "TR"},
        {"code": "Burdur", "category": "TR"},
        {"code": "Bursa", "category": "TR"},
        {"code": "Çanakkale", "category": "TR"},
        {"code": "Çankırı", "category": "TR"},
        {"code": "Çorum", "category": "TR"},
        {"code": "Denizli", "category": "TR"},
        {"code": "Diyarbakır", "category": "TR"},
        {"code": "Düzce", "category": "TR"},
        {"code": "Edirne", "category": "TR"},
        {"code": "Elazığ", "category": "TR"},
        {"code": "Erzincan", "category": "TR"},
        {"code": "Erzurum", "category": "TR"},
        {"code": "Eskişehir", "category": "TR"},
        {"code": "Gaziantep", "category": "TR"},
        {"code": "Giresun", "category": "TR"},
        {"code": "Gümüşhane", "category": "TR"},
        {"code": "Hakkâri", "category": "TR"},
        {"code": "Hatay", "category": "TR"},
        {"code": "Iğdır", "category": "TR"},
        {"code": "Isparta", "category": "TR"},
        {"code": "İstanbul", "category": "TR"},
        {"code": "İzmir", "category": "TR"},
        {"code": "Kahramanmaraş", "category": "TR"},
        {"code": "Karabük", "category": "TR"},
        {"code": "Karaman", "category": "TR"},
        {"code": "Kars", "category": "TR"},
        {"code": "Kastamonu", "category": "TR"},
        {"code": "Kayseri", "category": "TR"},
        {"code": "Kırıkkale", "category": "TR"},
        {"code": "Kırklareli", "category": "TR"},
        {"code": "Kırşehir", "category": "TR"},
        {"code": "Kilis", "category": "TR"},
        {"code": "Kocaeli", "category": "TR"},
        {"code": "Konya", "category": "TR"},
        {"code": "Kütahya", "category": "TR"},
        {"code": "Malatya", "category": "TR"},
        {"code": "Manisa", "category": "TR"},
        {"code": "Mardin", "category": "TR"},
        {"code": "Mersin", "category": "TR"},
        {"code": "Muğla", "category": "TR"},
        {"code": "Muş", "category": "TR"},
        {"code": "Nevşehir", "category": "TR"},
        {"code": "Niğde", "category": "TR"},
        {"code": "Ordu", "category": "TR"},
        {"code": "Osmaniye", "category": "TR"},
        {"code": "Rize", "category": "TR"},
        {"code": "Sakarya", "category": "TR"},
        {"code": "Samsun", "category": "TR"},
        {"code": "Siirt", "category": "TR"},
        {"code": "Sinop", "category": "TR"},
        {"code": "Sivas", "category": "TR"},
        {"code": "Şanlıurfa", "category": "TR"},
        {"code": "Şırnak", "category": "TR"},
        {"code": "Tekirdağ", "category": "TR"},
        {"code": "Tokat", "category": "TR"},
        {"code": "Trabzon", "category": "TR"},
        {"code": "Tunceli", "category": "TR"},
        {"code": "Uşak", "category": "TR"},
        {"code": "Van", "category": "TR"},
        {"code": "Yalova", "category": "TR"},
        {"code": "Yozgat", "category": "TR"},
        {"code": "Zonguldak", "category": "TR"},
        {"code": "Arima", "category": "TT"},
        {"code": "Chaguanas", "category": "TT"},
        {"code": "Couva/Tabaquite/Talparo", "category": "TT"},
        {"code": "Diego Martin", "category": "TT"},
        {"code": "Eastern Tobago", "category": "TT"},
        {"code": "Mayaro/Rio Claro", "category": "TT"},
        {"code": "Penal/Debe", "category": "TT"},
        {"code": "Point Fortin", "category": "TT"},
        {"code": "Port of Spain", "category": "TT"},
        {"code": "Princes Town", "category": "TT"},
        {"code": "San Fernando", "category": "TT"},
        {"code": "Sangre Grande", "category": "TT"},
        {"code": "San Juan/Laventille", "category": "TT"},
        {"code": "Siparia", "category": "TT"},
        {"code": "Tunapuna/Piarco", "category": "TT"},
        {"code": "Western Tobago", "category": "TT"},
        {"code": "Changhua County", "category": "TW"},
        {"code": "Chiayi County", "category": "TW"},
        {"code": "Chiayi City", "category": "TW"},
        {"code": "Hsinchu County", "category": "TW"},
        {"code": "Hsinchu City", "category": "TW"},
        {"code": "Hualien County", "category": "TW"},
        {"code": "Yilan County", "category": "TW"},
        {"code": "Kaohsiung County", "category": "TW"},
        {"code": "Kaohsiung City", "category": "TW"},
        {"code": "Keelung City", "category": "TW"},
        {"code": "Miaoli County", "category": "TW"},
        {"code": "Nantou County", "category": "TW"},
        {"code": "Penghu County", "category": "TW"},
        {"code": "Pingtung County", "category": "TW"},
        {"code": "Taichung County", "category": "TW"},
        {"code": "Taichung City", "category": "TW"},
        {"code": "Tainan County", "category": "TW"},
        {"code": "Tainan City", "category": "TW"},
        {"code": "Taipei County", "category": "TW"},
        {"code": "Taipei City", "category": "TW"},
        {"code": "Taitung County", "category": "TW"},
        {"code": "Taoyuan County", "category": "TW"},
        {"code": "Yunlin County", "category": "TW"},
        {"code": "AL", "category": "US"},
        {"code": "AK", "category": "US"},
        {"code": "AZ", "category": "US"},
        {"code": "AR", "category": "US"},
        {"code": "CA", "category": "US"},
        {"code": "CO", "category": "US"},
        {"code": "CT", "category": "US"},
        {"code": "DC", "category": "US"},
        {"code": "DE", "category": "US"},
        {"code": "FL", "category": "US"},
        {"code": "GA", "category": "US"},
        {"code": "HI", "category": "US"},
        {"code": "ID", "category": "US"},
        {"code": "IL", "category": "US"},
        {"code": "IN", "category": "US"},
        {"code": "IA", "category": "US"},
        {"code": "KS", "category": "US"},
        {"code": "KY", "category": "US"},
        {"code": "LA", "category": "US"},
        {"code": "ME", "category": "US"},
        {"code": "MD", "category": "US"},
        {"code": "MA", "category": "US"},
        {"code": "MI", "category": "US"},
        {"code": "MN", "category": "US"},
        {"code": "MS", "category": "US"},
        {"code": "MO", "category": "US"},
        {"code": "MP", "category": "US"},
        {"code": "MT", "category": "US"},
        {"code": "NE", "category": "US"},
        {"code": "NV", "category": "US"},
        {"code": "NH", "category": "US"},
        {"code": "NJ", "category": "US"},
        {"code": "NM", "category": "US"},
        {"code": "NY", "category": "US"},
        {"code": "NC", "category": "US"},
        {"code": "ND", "category": "US"},
        {"code": "OH", "category": "US"},
        {"code": "OK", "category": "US"},
        {"code": "OR", "category": "US"},
        {"code": "PA", "category": "US"},
        {"code": "RI", "category": "US"},
        {"code": "SC", "category": "US"},
        {"code": "SD", "category": "US"},
        {"code": "TN", "category": "US"},
        {"code": "TX", "category": "US"},
        {"code": "UT", "category": "US"},
        {"code": "VT", "category": "US"},
        {"code": "VA", "category": "US"},
        {"code": "WA", "category": "US"},
        {"code": "WV", "category": "US"},
        {"code": "WI", "category": "US"},
        {"code": "WY", "category": "US"},
        {"code": "GU", "category": "US"},
        {"code": "PR", "category": "US"},
        {"code": "VI", "category": "US"},
        {"code": "XX", "category": "US"},
        {"code": "Dependencias Federales", "category": "VE"},
        {"code": "Distrito Capital", "category": "VE"},
        {"code": "Amazonas", "category": "VE"},
        {"code": "Anzoátegui", "category": "VE"},
        {"code": "Apure", "category": "VE"},
        {"code": "Aragua", "category": "VE"},
        {"code": "Barinas", "category": "VE"},
        {"code": "Bolívar", "category": "VE"},
        {"code": "Carabobo", "category": "VE"},
        {"code": "Cojedes", "category": "VE"},
        {"code": "Delta Amacuro", "category": "VE"},
        {"code": "Falcón", "category": "VE"},
        {"code": "Guárico", "category": "VE"},
        {"code": "Lara", "category": "VE"},
        {"code": "Merida !Mérida", "category": "VE"},
        {"code": "Miranda", "category": "VE"},
        {"code": "Monagas", "category": "VE"},
        {"code": "Nueva Esparta", "category": "VE"},
        {"code": "Portuguesa", "category": "VE"},
        {"code": "Sucre", "category": "VE"},
        {"code": "Tachira !Táchira", "category": "VE"},
        {"code": "Trujillo", "category": "VE"},
        {"code": "Vargas", "category": "VE"},
        {"code": "Yaracuy", "category": "VE"},
        {"code": "Zulia", "category": "VE"},
        {"code": "Saint Croix - Anna's Hope Village", "category": "VI"},
        {"code": "Saint Croix - Christiansted", "category": "VI"},
        {"code": "Saint Croix - East End", "category": "VI"},
        {"code": "Saint Croix - Frederiksted", "category": "VI"},
        {"code": "Saint Croix - Northcentral", "category": "VI"},
        {"code": "Saint Croix - Northwest", "category": "VI"},
        {"code": "Saint Croix - Sion Farm", "category": "VI"},
        {"code": "Saint Croix - Southcentral", "category": "VI"},
        {"code": "Saint Croix - Southwest", "category": "VI"},
        {"code": "Saint Thomas - Charlotte Amalie", "category": "VI"},
        {"code": "Saint Thomas - East End", "category": "VI"},
        {"code": "Saint Thomas - Northside", "category": "VI"},
        {"code": "Saint Thomas - Southside", "category": "VI"},
        {"code": "Saint Thomas - Tutu", "category": "VI"},
        {"code": "Saint Thomas - Water Island", "category": "VI"},
        {"code": "Saint Thomas - West End", "category": "VI"},
        {"code": "Saint John - Central", "category": "VI"},
        {"code": "Saint John - Coral Bay", "category": "VI"},
        {"code": "Saint John - Cruz Bay", "category": "VI"},
        {"code": "Saint John - East End", "category": "VI"},
        {"code": "An Giang", "category": "VN"},
        {"code": "Bà Rịa–Vũng Tàu", "category": "VN"},
        {"code": "Bạc Liêu", "category": "VN"},
        {"code": "Bắc Giang", "category": "VN"},
        {"code": "Bắc Kạn", "category": "VN"},
        {"code": "Bắc Ninh", "category": "VN"},
        {"code": "Bến Tre", "category": "VN"},
        {"code": "Bình Dương", "category": "VN"},
        {"code": "Bình Định", "category": "VN"},
        {"code": "Bình Phước", "category": "VN"},
        {"code": "Bình Thuận", "category": "VN"},
        {"code": "Cà Mau", "category": "VN"},
        {"code": "Cao Bằng", "category": "VN"},
        {"code": "Cần Thơ", "category": "VN"},
        {"code": "Đà Nẵng", "category": "VN"},
        {"code": "Đắk Lắk", "category": "VN"},
        {"code": "Đắk Nông", "category": "VN"},
        {"code": "Điện Biên", "category": "VN"},
        {"code": "Đồng Nai", "category": "VN"},
        {"code": "Đồng Tháp ", "category": "VN"},
        {"code": "Gia Lai", "category": "VN"},
        {"code": "Hà Giang", "category": "VN"},
        {"code": "Hà Nam", "category": "VN"},
        {"code": "Hà Nội", "category": "VN"},
        {"code": "Hà Tây", "category": "VN"},
        {"code": "Hà Tĩnh", "category": "VN"},
        {"code": "Hải Dương", "category": "VN"},
        {"code": "Hải Phòng", "category": "VN"},
        {"code": "Hậu Giang", "category": "VN"},
        {"code": "Hòa Bình", "category": "VN"},
        {"code": "Hồ Chí Minh (Sài Gòn)", "category": "VN"},
        {"code": "Hưng Yên", "category": "VN"},
        {"code": "Khánh Hòa", "category": "VN"},
        {"code": "Kiên Giang", "category": "VN"},
        {"code": "Kon Tum", "category": "VN"},
        {"code": "Lai Châu", "category": "VN"},
        {"code": "Lạng Sơn", "category": "VN"},
        {"code": "Lào Cai", "category": "VN"},
        {"code": "Lâm Đồng", "category": "VN"},
        {"code": "Long An", "category": "VN"},
        {"code": "Nam Định", "category": "VN"},
        {"code": "Nghệ An", "category": "VN"},
        {"code": "Ninh Bình", "category": "VN"},
        {"code": "Ninh Thuận", "category": "VN"},
        {"code": "Phú Thọ", "category": "VN"},
        {"code": "Phú Yên", "category": "VN"},
        {"code": "Quảng Bình", "category": "VN"},
        {"code": "Quảng Nam", "category": "VN"},
        {"code": "Quảng Ngãi", "category": "VN"},
        {"code": "Quảng Ninh", "category": "VN"},
        {"code": "Quảng Trị", "category": "VN"},
        {"code": "Sóc Trăng", "category": "VN"},
        {"code": "Sơn La", "category": "VN"},
        {"code": "Tây Ninh", "category": "VN"},
        {"code": "Thái Bình", "category": "VN"},
        {"code": "Thái Nguyên", "category": "VN"},
        {"code": "Thanh Hóa", "category": "VN"},
        {"code": "Thừa Thiên–Huế", "category": "VN"},
        {"code": "Tiền Giang", "category": "VN"},
        {"code": "Trà Vinh", "category": "VN"},
        {"code": "Tuyên Quang", "category": "VN"},
        {"code": "Vĩnh Long", "category": "VN"},
        {"code": "Vĩnh Phúc", "category": "VN"},
        {"code": "Yên Bái", "category": "VN"},
        {"code": "Eastern Cape", "category": "ZA"},
        {"code": "Free State", "category": "ZA"},
        {"code": "Gauteng", "category": "ZA"},
        {"code": "KwaZulu-Natal", "category": "ZA"},
        {"code": "Limpopo", "category": "ZA"},
        {"code": "Mpumalanga", "category": "ZA"},
        {"code": "Northern Cape", "category": "ZA"},
        {"code": "North West", "category": "ZA"},
        {"code": "Western Cape", "category": "ZA",
        }
    ]
}
end
