clientID:       <%= ENV['YAML_ADP_SUBSCRIPTION_CLIENT_ID'] %>
clientSecret:   <%= ENV['YAML_ADP_SUBSCRIPTION_CLIENT_SECRET'] %>
sslCertPath:    config/certs/apiclient_certificate.pem
sslKeyPath:     config/certs/apiclient_private.key
sslKeyPass:     ''
tokenServerURL: https://api.adp.com/auth/oauth/v2/token
disconnectURL:  https://accounts.adp.com/auth/oauth/v2/logout
apiRequestURL:  https://api.adp.com
responseType:   code
defaultexpiration: 3600
grantType:      client_credentials