development:
  secret_key_base: f2fc4bc55b372480fb3ff29bd2e7253a938cb021d9cb77ee555f707b65cb5a246f99405bd59643bc1e392c77e7c3849733b81de7ff36cce8bebece5f7e58fb5d

test:
  secret_key_base: d81de029f53ceada7d97b5cfd28d8d534b8d31ba062d3bcd35dd376828ece8ec6c1fc4ced987df211689071b3b603ef7fbbf4da3b083ca57b9b158dac0184241

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

demo:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

fuse:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

release:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

spades:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
