:concurrency: <%= (if ENV['SIDEKIQ_USER_BIG__SCHEDULE_REPORTS_CONCURRENCY'].to_i > 0 then ENV['SIDEKIQ_USER_BIG__SCHEDULE_REPORTS_CONCURRENCY'].to_i else 2 end) %>
:pidfile: tmp/pids/sidekiq-user-big-report.pid
:queues:
  - big_user_schedule_report
