EMAIL_TYPES = { invitation: 'Onboarding', welcome_email: 'Welcome Email', offboarding: 'Offboarding' }.freeze

EMAIL_TOKENS =  [
  'Hire First Name',
  'First Name',
  'Last Name',
  'Hire Preferred/ First Name',
  'Preferred/ First Name',
  'Hire Full Name',
  'Full Name',
  'Hire Title',
  'Job Title',
  'Manager First Name',
  'Manager Full Name',
  'Manager Title',
  'Manager Email',
  'Hire Location',
  'Location',
  'Hire Start Date',
  'Start Date',
  'Activity Owner First Name',
  'Activity Count',
  'Activity Owner Email',
  'Task Owner First Name',
  'Task Owner Email',
  'Task Count',
  'Document Name',
  'Termination Date',
  'Last Day',
  'Personal Email',
  'Company Email',
  'Employment Status',
  'Old Start Date',
  'Last Day Worked',
  'Current Start Date',
  'New Start Date',
  'Termination type',
  'Eligible for Rehire',
  'Access Permission',
  'Status',
  'About',
  'Facebook',
  'LinkedIn',
  'Twitter',
  'Github',
  'Company Name'
].freeze

DEFAULT_NOTIFICATION_TEMPLATES = [
  'manager_form',
  'preboarding',
  'new_activites_assigned',
  'new_manager_form',
  'document_completion',
  'onboarding_activity_notification',
  'transition_activity_notification',
  'offboarding_activity_notification',
  'new_manager',
  'new_buddy',
  'new_pending_hire',
  'start_date_change',
  'invite_user',
  'onboarding_invitation'
].freeze
