class Survey < ApplicationRecord
  acts_as_paranoid
  validates :company, :name, :estimated_time, :survey_type, presence: true
  belongs_to :company
  validates :name, uniqueness: { scope: :company_id }
  has_many :tasks, dependent: :nullify
  has_many :survey_questions, dependent: :destroy

  enum survey_type: { onboarding: 0, offboarding: 1, general: 2 }

  def self.create_default_surveys(company)
    return if company.surveys.count > 0 || company.nil?

    survey = company.surveys.create(survey_type: Survey.survey_types[:onboarding], name: "1st Week Check-In", estimated_time: 3)
    survey.survey_questions.create(position: 0, category: 0, question_text: "The primary reasons I decided to take this position are:", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 1, category: 0, question_text: "Describe what you were doing before working here:", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 2, category: 1, question_text: "I received useful information about my first week here before my start date.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 3, category: 1, question_text: "I received accurate information about my first week here before my start date.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 4, category: 2, question_text: "I'm feeling welcomed here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 5, category: 2, question_text: "I'm proud to work here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 6, category: 2, question_text: "I'm feeling productive.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 7, category: 2, question_text: "What's one thing we could have done differently to improve your first week?", question_type: SurveyQuestion.question_types[:long_text])

    survey = company.surveys.create(survey_type: Survey.survey_types[:onboarding], name: "1st Month Check-In", estimated_time: 8)
    survey.survey_questions.create(position: 0, category: 3, question_text: "I would recommend [CompanyName] as a great place to work.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 1, category: 3, question_text: "I rarely think about looking for a job at another company.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 2, category: 3, question_text: "I see myself still working here in two years' time.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 3, category: 4, question_text: "[CompanyName] motivates me to go beyond what I would in a similar role elsewhere.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 4, category: 4, question_text: "I'm confident using the systems I need in my role.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 5, category: 4, question_text: "I have had good training on the processes applicable to my role.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 6, category: 4, question_text: "I have a good idea about what I still need to learn to do my job well.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 7, category: 4, question_text: "The information provided has been at the right level for me.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 8, category: 5, question_text: "The values of [CompanyName] align well with my own values.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 9, category: 5, question_text: "I understand how my role contributes to our company goals.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 10, category: 5, question_text: "My role so far matches the role description provided to me.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 11, category: 5, question_text: "I still feel like this is a great role for me.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 12, category: 2, question_text: "I'm feeling welcomed here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 13, category: 2, question_text: "I'm proud to work here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 14, category: 2, question_text: "I'm feeling productive.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 15, category: 2, question_text: "What's one thing we could have done differently to improve your first month?", question_type: SurveyQuestion.question_types[:long_text])

    survey = company.surveys.create(survey_type: Survey.survey_types[:onboarding], name: "90-Day Check-In", estimated_time: 8)
    survey.survey_questions.create(position: 0, category: 3, question_text: "I would recommend [CompanyName] as a great place to work.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 1, category: 3, question_text: "I rarely think about looking for a job at another company.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 2, category: 3, question_text: "I see myself still working here in two years' time.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 3, category: 3, question_text: "[CompanyName] motivates me to go beyond what I would in a similar role elsewhere.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 4, category: 5, question_text: "I understand how my role contributes to our company goals.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 5, category: 5, question_text: "I still feel like this is a great role for me.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 6, category: 6, question_text: "My manager communicates clear goals for our team.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 7, category: 6, question_text: "My manager gives me actionable feedback on a regular basis.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 8, category: 7, question_text: "I can see myself growing and developing my career here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 9, category: 7, question_text: "I know what is expected of me at work.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 10, category: 7, question_text: "I have the tools and the resources to do my job.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 11, category: 7, question_text: "At work, I have the opportunity to do what I do best every day.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 12, category: 2, question_text: "I'm feeling welcomed here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 13, category: 2, question_text: "I'm proud to work here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 14, category: 2, question_text: "I'm feeling productive.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 15, category: 2, question_text: "What's one thing we could have done differently to improve your first three months?", question_type: SurveyQuestion.question_types[:long_text])

    survey = company.surveys.create(survey_type: Survey.survey_types[:offboarding], name: "Exit Survey", estimated_time: 9)
    survey.survey_questions.create(position: 0, category: 8, question_text: "I'm likely to recommend this company to a friend as a great place to work.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 1, category: 8, question_text: "In just a few words, describe what factors influenced your decision to leave?", question_type: SurveyQuestion.question_types[:short_text])
    survey.survey_questions.create(position: 2, category: 8, question_text: "What did you like most about your job?", question_type: SurveyQuestion.question_types[:short_text])
    survey.survey_questions.create(position: 3, category: 8, question_text: "What did you like least about your job?", question_type: SurveyQuestion.question_types[:short_text])
    survey.survey_questions.create(position: 4, category: 9, question_text: "I was treated fairly by my manager.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 5, category: 9, question_text: "My manager and I communicated together well.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 6, category: 9, question_text: "My manager provided recognition for my work.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 7, category: 9, question_text: "I was treated as a valuable member of my team.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 8, category: 10, question_text: "The company was able to put my skills to good use.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 9, category: 10, question_text: "I was able to get all the resources needed to do my job successfully at this organization.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 10, category: 10, question_text: "I was paid well for the work I did here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 11, category: 10, question_text: "I was well trained to perform my job effectively.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 12, category: 11, question_text: "I enjoyed working here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 13, category: 11, question_text: "I felt safe working here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 14, category: 11, question_text: "I was kept well informed about our strategy and operations.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 15, category: 11, question_text: "I was kept well informed about our policies and procedures.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 16, category: 11, question_text: "I was able to balance my professional and personal goals during my time here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 17, category: 11, question_text: "Are there any additional suggestions you might have to improve our company?", question_type: SurveyQuestion.question_types[:long_text])

    survey = company.surveys.create(survey_type: Survey.survey_types[:general], name: "Wellness Check-In", estimated_time: 5)
    survey.survey_questions.create(position: 0, category: 12, question_text: "Everyone’s well-being is a priority here.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 1, category: 12, question_text: "My manager has checked in on my wellbeing in the last 7 days.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 2, category: 12, question_text: "My stress level is manageable.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 3, category: 12, question_text: "I am encouraged to take time for myself during the workday.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 4, category: 12, question_text: "I feel supported to adjust my work schedule to accommodate my caregiving needs for myself or others.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 5, category: 12, question_text: "I feel motivated to show up for work every day.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 6, category: 13, question_text: "I am able to maintain meaningful connections with my work friends.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 7, category: 13, question_text: "I feel comfortable bringing up work-related problems with my coworkers.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 8, category: 14, question_text: "I have the tools I need to work effectively.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 9, category: 14, question_text: "My manager effectively responds to my needs.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 10, category: 14, question_text: "My manager clearly communicates team and individual responsibilities.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 11, category: 14, question_text: "Is there any support you need at this time that you are not currently receiving?", question_type: SurveyQuestion.question_types[:long_text])

    survey = company.surveys.create(survey_type: Survey.survey_types[:general], name: "Performance Check-In (Open)", estimated_time: 4)
    survey.survey_questions.create(position: 0, category: 15, question_text: "Describe one way [Preferred Name / First Name] supports you and your team?", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 1, category: 15, question_text: "What types of traits or activities should [Preferred Name / First Name] continue doing?", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 2, category: 16, question_text: "What types of traits or activities should [Preferred Name / First Name] stop doing?", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 3, category: 16, question_text: "What types of traits or activities should [Preferred Name / First Name] start doing?", question_type: SurveyQuestion.question_types[:long_text])

    survey = company.surveys.create(survey_type: Survey.survey_types[:general], name: "Performance Check-In (Measured)", estimated_time: 12)
    survey.survey_questions.create(position: 0, category: 17, question_text: "Relative to peers, [Preferred Name / First Name] keeps control of their emotions and behavior, even when involved in high-pressure situations.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 1, category: 17, question_text: "Relative to peers, [Preferred Name / First Name] is highly ethical.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 2, category: 17, question_text: "Relative to peers, [Preferred Name / First Name] acts professionally.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 3, category: 17, question_text: "Relative to peers, [Preferred Name / First Name] learns from their mistakes.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 4, category: 18, question_text: "Relative to peers, [Preferred Name / First Name] is focused on the needs of their customer.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 5, category: 18, question_text: "Relative to peers, [Preferred Name / First Name] is a problem-solver.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 6, category: 19, question_text: "Relative to peers, [Preferred Name / First Name] communicates openly and effectively with others.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 7, category: 19, question_text: "Relative to peers, [Preferred Name / First Name] is open and receptive to feedback or seeks out feedback.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 8, category: 20, question_text: "Relative to peers, [Preferred Name / First Name] inspires continuous growth and learning in others.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 9, category: 20, question_text: "Relative to peers, [Preferred Name / First Name] handles conflict in an appropriate manner.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 10, category: 20, question_text: "Relative to peers, [Preferred Name / First Name] takes initiative to solve problems.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 11, category: 20, question_text: "Relative to peers, [Preferred Name / First Name] motivates others to reach their goals.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 12, category: 21, question_text: "Relative to peers, [Preferred Name / First Name] gives constructive and helpful feedback.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 13, category: 21, question_text: "Relative to peers, [Preferred Name / First Name] treats others with respect.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 14, category: 21, question_text: "Relative to peers, [Preferred Name / First Name] responds constructively to others’ mistakes.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 15, category: 21, question_text: "Relative to peers, [Preferred Name / First Name] is open to change and innovation.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 16, category: 15, question_text: "[Preferred Name / First Name] contributes to my ability to do my job well.", question_type: SurveyQuestion.question_types[:likert])
    survey.survey_questions.create(position: 17, category: 15, question_text: "What types of traits or activities should [Preferred Name / First Name] continue doing?", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 18, category: 16, question_text: "What types of traits or activities should [Preferred Name / First Name] stop doing?", question_type: SurveyQuestion.question_types[:long_text])
    survey.survey_questions.create(position: 19, category: 16, question_text: "What types of traits or activities should [Preferred Name / First Name] start doing?", question_type: SurveyQuestion.question_types[:long_text])

    self.create_ona_survey(company)
  end

  def self.create_ona_survey(company)
    return if company.surveys.where(name: "Organizational Network Analysis").count > 0 || company.nil?
    survey = company.surveys.create(survey_type: Survey.survey_types[:general], name: "Organizational Network Analysis", estimated_time: 12)
    survey.survey_questions.create(position: 0, category: 22, question_text: "List up to 3 team members who provide you information critical to doing your job.", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 1, category: 23, question_text: "List up to 3 team members you communicate with throughout the week.", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 2, category: 24, question_text: "List up to 3 team members who make you more effective at doing your job well.", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 3, category: 25, question_text: "List up to 3 team members who energize you the most about your job and working at [CompanyName].", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 4, category: 26, question_text: "List up to 3 team members who help you solve problems encountered in your job.", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 5, category: 27, question_text: "List up to 3 team members you are likely to turn to when you have a new idea to propose.", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 6, category: 28, question_text: "List up to 3 team members you ask for input before making a decision.", question_type: SurveyQuestion.question_types[:person_lookup])
    survey.survey_questions.create(position: 7, category: 29, question_text: "List up to 3 team members you know the best in terms of their knowledge and skills (i.e. you know exactly how they can help you or the company).", question_type: SurveyQuestion.question_types[:person_lookup])
  end

end
